.gitignore, config/environment.js, cordova/config.xml, cordova/hooks/README.md, package.json
=> integrated ember-cli-cordova

app/components/dispatch-form.js, app/locales/en/translations.coffee, app/locales/zh-tw/translations.coffee, app/models/designation.js
Hi,
This is PR shows an alert message when all items from order are dispatched.
Thanks.
=> GCW-1105:display close-order alert-message when all items from order are dispatched.

app/components/designate-form.js, app/controllers/orders/items.js, app/templates/orders/items.hbs
=> GCW-1109 auto-display designate overlay when search-results return matched one record

app/components/focus-textfield.js, app/styles/templates/orders/_index.scss
Hi,
This PR solves following issue:-
- Clearing search box should leave focus in search box.
Thanks
=> GCW-1110:Clearing search box should leave focus in search box.

app/controllers/authenticate.js, bower.json, package.json, tests/acceptance/login-test.js, tests/factories/mobile.js, tests/factories/user.js, tests/factories/user_profile.js
Hi,
I've added some test cases for login. Review it and let me know if any further changes are required.
Thanks.
=> Test cases for login

package.json, tests/acceptance/item-test.js, tests/acceptance/order-test.js, tests/factories/code.js, tests/factories/contact.js, tests/factories/designation.js, tests/factories/item.js, tests/factories/location.js, tests/factories/package.js, tests/factories/package_type.js, tests/factories/schedule.js, tests/helpers/start-app.js
Hi,
Test cases added for Orders and Items tab.
Thanks
=> Test cases for Orders page

app/components/image-zoom.js, app/templates/components/image-zoom.hbs, app/templates/items/detail.hbs, bower.json, ember-cli-build.js
Hi, 
This PR allows user to zoom-in/zoom-out the image.
Thanks
=> Gcw 1160 image zoom

app/components/image-zoom.js, app/styles/_main.scss, app/templates/components/image-zoom.hbs, cordova/config.xml
Hi,
This PR adds Cordova PhotoViewer Addon for image-zoom.
Thanks.
=> GCW-1064: Cordova PhotoViewer addon added for image-zoom

app/styles/templates/_index.scss, app/styles/templates/items/_detail.scss, app/templates/items/_multiple_set_item_images.hbs, app/templates/items/detail.hbs
Hi
This PR fixes some issue for ticket GCW-1160
Thanks
=> GCW 1160 fixes

app/styles/app.scss, app/styles/templates/items/_index.scss, app/styles/templates/orders/_items.scss, app/templates/items/index.hbs
Hi,
This PR disables horizontal-scrolling for stock app.
Thanks.
=> GCW-1211 horizontal-scrolling disabled for stock-app

app/components/scan-barcode-for-location.js, app/controllers/items/new.js, app/controllers/items/search_location.js, app/routes/items/new.js, app/styles/templates/items/_new.scss, app/styles/templates/orders/_index.scss, app/templates/components/scan-barcode-for-location.hbs, app/templates/items/new.hbs, app/templates/items/search_location.hbs
Hi,
This PR adds barcode scanner for location.
Thanks
=> GCW-1194 component added for location-scan

app/components/scan-barcode-button.js, app/templates/items/new.hbs
Hi,
This PR handles prefix 'X' on barcode capture.
Thanks
=> GCW-1212 handle prefix 'X' on barcode capture

app/controllers/items/search_location.js
Hi,
This PR adds triggerDisplayMoveOverlay which pops up an overlay if entered location has exact same match.
Thanks
=> GCW-1194 trigger-Display-Move-Overlay added for exact match of location

app/routes/items/search_location.js, app/routes/items/search_order.js, app/templates/items/_item_back_link.hbs, app/templates/items/search_location.hbs, app/templates/items/search_order.hbs
Hi Team,
This PR handles navigation issue issue for individual item.
Thanks
=> handle back link for item move

app/components/barcode-scanner.js, app/controllers/items/new.js, app/templates/components/barcode-scanner.hbs, app/templates/components/location-barcode-scanner.hbs, app/templates/items/new.hbs
Hi Team,
This PR enables scanner for donation.
Thanks.
=> GCW-1226 Enable scanner for donation

app/controllers/items/search_location.js, app/locales/en/translations.coffee, app/locales/zh-tw/translations.coffee, app/routes/items/search_location.js, app/styles/templates/components/_item_options.scss, app/styles/templates/components/_item_options_list.scss, app/templates/components/dispatch-form.hbs, app/templates/components/remove-item-from-set.hbs, app/templates/components/undesignate-item.hbs, app/templates/items/search_location.hbs
Hi,
This PR has some modifications in stock changes.
Thanks
=> GCW-1237 Stock- modifications to actions

app/controllers/items/search_order.js, app/controllers/search_module.js, app/models/designation.js, app/templates/orders/detail.hbs
Hi Team,
This PR is for restring user from adding new items to inactive orders.
Thanks.
=> GCW-1222-do-not-allow-to-add-items-to-inactive-order

app/components/barcode-scanner.js, app/components/inline-select-list.js, app/components/numeric-inline-input.js, app/components/text-inline-input.js, app/controllers/items/detail.js, app/routes/items/detail.js, app/styles/_custom.scss, app/styles/templates/items/_detail.scss, app/templates/items/_item_detail_block.hbs
Hi,
This PR adds ability of inline editing for user.
Thanks
=> GCW-1234 Stock item- Inline edit

.gitignore, Rakefile, circle.yml, cordova/config.xml, cordova/scripts/update_build_number.py, fastlane/Appfile, fastlane/Fastfile, fastlane/README.md, package.json, scripts/install-provisioning-file.sh
@steveyken changes to stock.goodcity for osx builds
=> Circleci osx build

app/controllers/orders/order_transport.js, app/models/designation.js, app/models/order_transport.js, app/router.js, app/routes/orders/order_transport.js, app/routes/orders/purposes.js, app/templates/orders/detail.hbs, app/templates/orders/order_transport.hbs, app/templates/orders/purposes.hbs
Reverts crossroads/stock.goodcity#187
=> Revert "Revert "Gcw 1367 build new orders view""

config/environment.js
Hi Team,
This PR contains changes to exclude transition aborted error in rollbar
Thanks
=> #DecemberRelease2

app/components/message-box.js, app/routes/session.js
Hi Team,
This PR contains following fixes:
1) Login click not working on login pop-up
2) Deleting AuthToken doesn't redirect to login
=> Bug fixes after upgrade

app/models/address.js, config/coverage.js, tests/acceptance/add-new-item-to-inventory-test.js, tests/controller/items/index-test.js, tests/factories/address.js, tests/factories/order_transport.js, tests/unit/model/address-test.js, tests/unit/model/code-test.js, tests/unit/model/order-transport-test.js, tests/unit/model/user-profile-test.js
Hi Team,
This PR improves code coverage by 1%
=> Test cases

app/routes/application.js
Hi Team,
This PR is for ticket: https://jira.crossroads.org.hk/browse/GCW-1846
Please review and let me know if any changes required.
Thanks.
=> unload ember data if auth token is not present local storage

app/controllers/items/new.js
Hi Team,
This PR is for ticket: https://jira.crossroads.org.hk/browse/GCW-1851
Please review and let me know if any changes are required.
Thanks.
=> GCW:1851:- Added seperate condition for new location and old location

app/components/barcode-scanner.js, app/components/donation-field.js, app/components/scan-barcode-button.js, app/controllers/items/new.js, cordova/config.xml
Hi,
This is pull request for jira ticket https://jira.crossroads.org.hk/browse/GCW-1850.
=> QR code added with new barcodescanner git url

app/controllers/application.js, app/controllers/index.js, app/locales/en/translations.coffee, app/locales/zh-tw/translations.coffee, app/styles/templates/_index.scss, app/templates/index.hbs
Hi Team,
This PR adds Logout link to Stock App
https://jira.crossroads.org.hk/browse/GCW-1876
=> GCW:- 1876 Logout button added to stock

app/templates/items/new.hbs, tests/acceptance/add-new-item-to-inventory-test.js
Hi,
This PR for test case of issue GCW-1851- https://jira.crossroads.org.hk/browse/GCW-1851.
Please review it.
Thanks
=> Test case added for gcw-1851

tests/acceptance/login-test.js
Hi Team,
This PR adds test cases for GCW:1876:- Add logout button to Stock
Jira Ticket:- https://jira.crossroads.org.hk/browse/GCW-1876
Improves test coverage by 1.7%
=> GCW-1876 Login and Logout test cases added

app/components/barcode-scanner.js, app/components/donation-field.js, app/components/scan-barcode-button.js, app/controllers/app_menu_list.js, app/controllers/items/new.js, app/styles/templates/_index.scss, app/templates/app_menu_list.hbs, app/templates/index.hbs, app/templates/sticky_footer.hbs
Hi Team,
This PR contains changes for : 
- Add logout button. https://jira.crossroads.org.hk/browse/GCW-1876
- Add test cases for custom location selection. (GCW-1851)
Thanks.
=> #MayRelease2

app/controllers/orders/detail.js, app/controllers/subscription.js, app/locales/en/translations.coffee, app/locales/zh-tw/translations.coffee, app/models/designation.js, app/models/orders_package.js, app/services/utility_methods.js, app/styles/templates/orders/_detail.scss, app/templates/orders/_order_status_bar.hbs, app/templates/orders/detail.hbs, tests/unit/model/designation-test.js, tests/unit/model/orders-package-test.js, tests/unit/model/set_item-test.js
Hi Team,
This PR adds state workflow for Order processing.
Jira Ticket:- https://jira.crossroads.org.hk/browse/GCW-1910
=> GCW-1910 stock order workflow

app/components/init-foundation.js, app/components/notification-bar.js, app/controllers/application.js, app/controllers/notifications.js, app/controllers/subscription.js, app/routes/application.js, app/styles/app.scss, app/styles/templates/_notifications.scss, app/templates/application.hbs, app/templates/notifications.hbs, bower.json, ember-cli-build.js
Hi Team,
This PR is for sending new gc order submission notification to order fulfilment user.
https://jira.crossroads.org.hk/browse/GCW-1909
Please review and let me know if any changes required.
Thanks.
=> notify order fulfilment user when new order submitted from browse app

app/components/item-options.js, app/controllers/orders/detail.js, app/helpers/capitalize-string.js, app/locales/en/translations.coffee, app/locales/zh-tw/translations.coffee, app/models/designation.js, app/styles/templates/orders/_detail.scss, app/templates/components/cancelled-order-options.hbs, app/templates/components/item-options.hbs, app/templates/orders/_cancelled_orders_packages.hbs, app/templates/orders/_order_status_bar.hbs, app/templates/orders/detail.hbs, app/templates/orders/orders_packages.hbs
Hi Team,
This PR adds feature to redisgnate an item to same order again
Jira Ticket:- https://jira.crossroads.org.hk/browse/GCW-1955
=> GCW:1955 redesignate cancelled orders-pacakge

cordova/config.xml
Hi Team,
This PR is to change camera access permission message for ios.
Please review and let me know if any changes required.
Thanks.
=> added new message to ask user for camera access permission

app/templates/items/modify_designation.hbs
Hi,
This is PR for GCW-1966 Wrong message on Item undesignate.
Thanks
=> Undesignate message changed

app/mixins/singleton_item_dispatch_to_gc_order.js
Hi Team,
This PR fixes bug that prevents item from dispatching from GC order.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-1995
RollBar link:- https://rollbar.com/crossroads_it/stock.goocity/items/242/
=> GCW-1995 Item dispatch fails on Order detail screen

app/mixins/singleton_item_dispatch_to_gc_order.js, circle.yml, package.json
Hi Team, 
This PR contains changes for : 
- Node upgrade to 6.0 
- Fix rollbar issue : https://rollbar.com/crossroads_it/stock.goocity/items/242/  (GCW-1995)
Please review.
Thanks.
=> #JuneRelease2

app/controllers/orders/contact.js, app/models/designation.js, app/templates/orders/contact.hbs, app/templates/orders/detail.hbs, tests/acceptance/order-organisation-and-contact-test.js, tests/factories/designation.js
Hi Team,
This PR uses Order submission detail to show User contact information.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2005
=> GCW-2005 Order contact detail

app/controllers/orders/detail.js, app/locales/en/translations.coffee, app/locales/zh-tw/translations.coffee, app/templates/orders/_order_status_bar.hbs
Hi Team,
This PR fixes Order process bug
- User is able to complete finishing process of the Order even if items are in cancelled state(Fixed)
Jira Ticket:- https://jira.crossroads.org.hk/browse/GCW-2002
=> GCW-2002 Finish order process bug

app/routes/orders/detail.js
Hi Team,
This PR is to fix rollabr issue: https://rollbar.com/crossroads_it/stock.goocity/items/263/
Please review and let me know if any changes required.
Thanks.
=> GCW-2029 fix rollbar issue for notifications

app/styles/templates/components/_message_box.scss, app/templates/items/modify_designation.hbs
Hi Team,
This is PR for GCW-1966- cancel bug NO. 3. 
https://jira.crossroads.org.hk/browse/GCW-1966.
I have added responsive code for medium size screen. Also changed the text for "Cancel" button.
Thanks
=> Gcw 1966 button text issue

app/controllers/orders/detail.js, app/services/app-review.js, config/environment.js, cordova/config.xml
Hi Team,
This PR adds feature for inapp review.
- whenever any order is closed User is prompt with review modal saying would you like to review out app. 
- For Android it redirects to playstore and for IOS inapp review is available
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-1920
Please review it and let me know if any other changes are required
Thanks
=> GCW-1920 Apprate poc

app/controllers/orders/detail.js
Hi Team,
This PR fixes issue of loading of app-rate plugin on android devices.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2051
Please review it and let me know if any other changes are required.
Thanks
=> GCW:2051 Close Order app-rate issue fixed

app/controllers/subscription.js
Hi Team,
This PR fixes issue of live update sync between of un-designation an Item between StockIt and Stock.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2080
Please review it and let me know if any other changes are required.
Thanks
=> GCW-2080 live update fix

app/controllers/application.js, app/routes/application.js, app/routes/session.js, app/services/cordova.js, circle.yml, cordova/config.xml, cordova/google-services.json
Hi,
This is PR for testing push notification on staging environment.
https://jira.crossroads.org.hk/browse/GCW-1909.
Please let me know if any change is required.
Thanks.
=> Gcw 1909 order fulfillment push notification

app/controllers/notifications.js, app/services/cordova.js, config/environment.js
Hi Team,
This is PR for GCW-1909- push notification.
https://jira.crossroads.org.hk/browse/GCW-1909
I have refactored the pushNotification code and also added code to redirect user on notification click to particular order_id.
Thanks
=> on tap notification redirected to order

Gemfile.lock
Hi Team,
This PR fixes : security vulnerability detected in rubyzip
Please review.
Thanks.
=> fix rubyzip vulnerability

app/services/cordova.js, circle.yml, cordova/config.xml
Hi Team,
This PR contains fix added for ios build failure. 
Thanks @Darshan-Chauhan   
Everyone, Please review.
Thanks.
=> Ios live fix release

app/components/request-inline-input.js, app/styles/templates/orders/_request.scss
Hi Team,
This PR fixes issue of request quantity inline edit allowing to set nil values.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2142
Please review it and let me know.
Thanks
=> GCW-2142 Request quantity field inline edit bug fix

app/templates/orders/_order_status_bar.hbs
Hi Team,
This PR fixes issue of users unable to close the order is all items are cancelled.
Jira ticket: https://jira.crossroads.org.hk/browse/GCW-2150
Please review it and let me know if further changes are required. 
Thanks
=> GCW-2150 Order close issue fixed

app/controllers/orders/detail.js, app/mixins/singleton_item_dispatch_to_gc_order.js, app/templates/components/item-options-list.hbs, app/templates/components/item-options.hbs, app/templates/items/detail.hbs
Hi Team,
This PR fixes issue of item dispatch on order detail screen.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2151
Please review it and let me know if further changes are required.
=> GCW-2151 dispatch item issue

app/routes/orders/add_request.js
Hi Team,
This PR fixes issue of quantity not setting to 1 default after adding a request.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2162
Please take a look and let me know if any other changes are required. 
Thanks
=> GCW-2162 reset quantity fix

app/controllers/items/search_location.js
Hi Team,
This Pr fixes roll bar issue for location not found messageBox popup
Rollbar Link:- https://rollbar.com/crossroads_it/stock.goocity/items/376/
=> RollBar Fix

app/components/focus-textfield.js, app/controllers/items/search_order.js, app/controllers/search_module.js, app/routes/index.js, app/routes/items/partial_designate.js, app/routes/items/search_order.js, app/templates/orders/order_block.hbs
Make results on the listing smaller as suggested by Matt. We're hiding the body and keeping the header. 
We're also fetching the designations on that page without any associations to improve performance
=> GCW-2155 Fetch designations without associations

app/controllers/items/index.js, app/controllers/search_module.js
Depends on : https://github.com/crossroads/api.goodcity/pull/571
This change just sends additional query options when doing the search request
=> FIX: Items search only displays received items

app/controllers/authenticate.js, config/environment.js
Hi Team,
This is PR for User to Redirect on attempted route after login. This changes has been added as a part of ticket GCW-2153 - Redirecting user to stock app after clicking inventory number in browse app.
https://jira.crossroads.org.hk/browse/GCW-2153
Please review the change and let me know if anything is required.
Thanks.
=> Fix #GCW-2153 - Redirect to attempted URL after login

app/components/message-box.js, app/components/quantity-chooser.js, app/controllers/orders/items.js, app/controllers/search_module.js, app/locales/en/translations.coffee, app/locales/zh-tw/translations.coffee, app/styles/_custom.scss, app/templates/components/quantity-chooser.hbs, app/templates/items/_item_detail_block.hbs, app/templates/items/detail.hbs, app/templates/items/partial_undesignate.hbs
Hi Team,
This PR contains following changes
- Adds package quantity splitting features
- Turns on ability to view quantity items
- Disables quantity features like partial designate/dispatch/move
- Disables view of quantity items on Orders/items search view
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2190
Please review and let me know if any other changes are required.
Thanks
**Note**: Test cases will be covered by @abhinav098 .
=> Split quantity feature

app/templates/components/quantity-chooser.hbs, app/templates/items/_item_detail_block.hbs, tests/acceptance/split-quantity-of-items-test.js
Hi team,
This PR is for adding acceptance test cases to the split-item-quantity feature.
Please review this and let me know if any changes are required.
Thanks
=> GCW-2190 split quantity acceptance tests

app/templates/orders/_orders_back_link_path.hbs
Hi, Team
This PR includes fix of Order back link issue when visiting order detail by clicking on notification.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2217
Please review and let me know if any further changes are required.
Thanks
=> GCW-2217 Order detail backlink issue

app/controllers/application.js, cordova/config.xml
Hi Team,
This is PR for ticket GCW-2165- Adding deeplinking for Android.
I have added deeplinking for android.
Thanks
=> Android deep Linking added

.circleci/config.yml, ember-cli-build.js
Hi Team,
This PR has following features:-
- Adds fingerprinting to JS files
- Uploads source map to rollbar
Jira tickets:- https://jira.crossroads.org.hk/browse/GCW-2214
Please review it and let me know if any changes are required. 
Thanks
=> GCW-2214 Fingerprinting and sourcemap

cordova/scripts/update_build_number.py
Hi Team,
This PR adds version seed to fix android release issue.
Thanks
=> Android versionCode seed added

config/environment.js
Hi team, this PR fixes the issue of app version.
Please review and comment.
Thanks.
=> GCW-2209 show app version

cordova/config.xml
Hi team this PR fixes the issue for camera on mobile apps.
Please review and comment.
Thanks
=> GCW-2262 fix camera take picture issue on android and ios

.circleci/config.yml, Gemfile.lock, Rakefile, cordova/config.xml
Hi team, this PR updates fastlane for iOS build.
=> Update fastlane and fix iOS build.

cordova/config.xml
Hi team, 
This PR fixes issue mentioned on ticket : https://jira.crossroads.org.hk/browse/GCW-2278
Please review.
Thanks.
=> fix plist issue

cordova/config.xml
Hi Team,
This PR fixes itunes plist issue.
https://jira.crossroads.org.hk/browse/GCW-2278
Please review.
Thanks.
=> #December2018Release4

app/templates/index.hbs, tests/acceptance/dashboard-test.js
Hi Team,
This is PR for Recent Order UI on dashboard.
Thanks
=> Recent order UI added

app/controllers/orders/detail.js, app/templates/orders/_orders_back_link_path.hbs
Hi Team,
This is back button fix from order details page to order page in filter applied state. Issue is fixed.
Thanks
=> back button from order to filter issue fixed

app/locales/en/translations.coffee
Hi Team,
This PR contains minor pop-up message change for cancel order as suggested by Matt on ticket: https://jira.crossroads.org.hk/browse/GCW-2294
I will ask Nokia or someone on engineering channel to do text changes in chinese for this ticket.
Please review.
Thanks.
=> Change cancel order pop-up message

app/helpers/type-filter-icon.js, app/models/designation.js, app/styles/templates/_index.scss, app/styles/templates/items/_detail.scss, app/styles/templates/items/_new.scss, app/styles/templates/items/_partial_undesignate.scss, app/styles/templates/orders/_index.scss, app/templates/components/remove-item-from-set.hbs, app/templates/index.hbs, app/templates/items/_location_filters.hbs, app/templates/items/partial_undesignate.hbs, app/templates/orders/_orders_back_link_path.hbs, app/templates/orders/order_transport.hbs, app/templates/orders/purposes.hbs, app/templates/orders/summary.hbs
Hi team, this PR fixes the issues reported by Tim on stock app regarding the new icons.
Please review and comment.
Thanks
=> GCW-2295 Upgrade font awesome icon fixes

app/components/item-filters.js, app/controllers/items/index.js, app/routes/items/index.js, app/services/filter-service.js, ember-cli-build.js, yarn.lock
Hello team, this is a child pr for item filters, where some minor ui improvements are done, so that filter automatically applys when filter is changed and text is present, also some refactoring.
Please review and comment.
=> GCW-2245 Item filter ui improvement

app/models/designation.js, app/models/order_transport.js, tests/acceptance/order-details-appointment-info-test.js
Hi @team, 
This PR contains changes for Booking type association changes. Please review and comment.
Thanks
=> GCW-2316 Booking type association changes.

app/locales/zh-tw/translations.coffee
Hi Team,
This adds chinese translation for order cancellation popup.
Please review.
Thanks.
=> add chinese translation for cancellation pop-up

app/components/item-filters.js, app/controllers/item_filters.js, app/templates/items/_location_filters.hbs
Hello team, 
This PR provides option for user to clear location filter. Please review and comment.
Thanks
=> GCW-2321 Provide option for user to remove locationFilter

cordova/config.xml
@Darshan-Chauhan @namrataukirde @abhinav098 @abulsayyad123 
All the changes were automatically made by the cordova command line.
I notice the `<engine name="android" spec="~6.3.0" />` was downgraded automatically to `<engine name="android" spec="~5.1.1" />` 
I assume that's wrong ?
=> FIX: update barcode scanner plugin

app/controllers/order/appointment_details.js, app/controllers/order/client_information.js, app/controllers/order/request_purpose.js, app/routes/order/appointment_details.js, app/styles/_appointment_details.scss, app/styles/_client_information.scss, app/styles/_main.scss, app/styles/_request_purpose.scss, app/styles/_search.scss, app/styles/templates/components/_add_request.scss, app/styles/templates/organisations/_search_organisations.scss, app/templates/app_menu_list.hbs, app/templates/components/add-request.hbs, app/templates/order/_user_information.hbs, app/templates/order/appointment_details.hbs, app/templates/order/booking_success.hbs, app/templates/order/client_information.hbs, app/templates/order/confirm_booking.hbs, app/templates/order/goods_details.hbs, app/templates/order/request_purpose.hbs, app/templates/order/search_users.hbs
Hi Team,
This is CSS fix for Order creation process. Please review the PR and let me know if any change is required.
=> Gcw 2246 - Order creation css fix

app/controllers/items/new.js, app/styles/templates/items/_new.scss, app/templates/items/new.hbs
Hi Team,
This PR adds a feature of publishing an item at the time of creation.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2324
Please review.
Thanks
=> GCW-2324 Allow Item publish at creation of item

app/components/item-filters.js, app/controllers/item_filters.js, app/controllers/items/index.js, app/routes/items/index.js
Hi Team,
This PR fixes bug of location filter not getting applied.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2325
Please review.
=> GCW-2325 Location filter fix

app/styles/templates/items/_index.scss, app/templates/items/index.hbs
Hi Team,
This PR is for CSS name conflict for `add_item_button`. Please review the PR and let me know if anything is required. 
Thanks
=> CSS common class name fix added

app/routes/index.js, app/styles/templates/_index.scss, app/templates/index.hbs, tests/acceptance/add-new-item-to-inventory-test.js, tests/acceptance/dashboard-test.js
Hi Team,
This PR is for JIRA ticket GCW-2151-Username not displayed on Dashboard Recent Orders. https://jira.crossroads.org.hk/browse/GCW-2351.
User Name is added along with associated test cases.
Please, review the PR and let me know if any change is required.
=> GCW-2351-User Name not displayed on Dashboard Recent Orders

app/styles/templates/_index.scss, app/templates/index.hbs
Hi Team,
This is responsive fix for the recent orders screen. Long Username were getting out of the list. It is fixed. Please, review the PR.
=> responsiveness fix

app/controllers/app_menu_list.js, app/controllers/authenticate.js, app/mixins/preload_data.js, app/routes/application.js, app/styles/_main.scss, app/templates/app_menu_list.hbs, app/templates/login.hbs, package.json
Hi Team,
This PR removes language-switcher for mobile devices to temporarily fix the issue and release the new features.
Please review.
Thanks
=> Language switcher fix

app/components/beneficiary-inline-input.js, app/components/beneficiary-inline-number-input.js, app/components/beneficiary-inline-select-list.js, app/components/numeric-inline-input.js, app/components/order-inline-number-input.js, app/components/order-inline-textarea-input.js, app/controllers/orders/client_summary.js, app/models/beneficiary.js, app/styles/templates/orders/_detail.scss, app/templates/orders/client_summary.hbs, tests/acceptance/purpose-test.js
Hi Team,
This PR includes inline edit feature for Order and beneficiary.
Please review.
Thanks
=> GCW-2365 Inline edit for beneficiary and order

app/controllers/orders/conversation.js, app/models/message.js
Hello team, this PR is for minor bug fix.
=> GCW-2425 fix async issue and auto scroll

config/environment.js, tests/acceptance/purpose-test.js, tests/acceptance/supervisor-user-footer-test.js
Hi Team,
This PR has `purpose` added in preload types and fix of related test cases.
=> Fix: Purpose added in authorized preload types

app/controllers/users/new.js, app/templates/users/new.hbs
Hi Team,
This PR contains changes for making mobile field optional while creating a user from the stock app.
Please review.
Thanks.
=> make mobile field optional for user creation

app/components/cancel-order.js, app/components/order-inline-number-input.js, app/controllers/order/client_information.js, app/styles/_client_information.scss, app/styles/templates/orders/_detail.scss, app/templates/order/client_information.hbs, app/templates/order/search_users.hbs, app/templates/orders/_summary_tabs.hbs, app/templates/orders/client_summary.hbs, app/templates/orders/contact_summary.hbs
Hi Team,
This PR has fixes for GCW:2365 Order's summary tab as per suggestions
Jira ticket: https://jira.crossroads.org.hk/browse/GCW-2365
Please review
=> GCW-2365 summary tab fixes

app/controllers/users/new.js, app/templates/users/new.hbs
Hi Team,
This PR contains changes to make mobile field optional while creating a user.
https://jira.crossroads.org.hk/browse/GCW-2344
Please review.
Thanks.
=> #Feab2019Release2

app/controllers/orders/detail.js, app/controllers/orders/order_types.js, app/locales/en/translations.coffee, app/locales/zh-tw/translations.coffee, app/models/designation.js, app/models/orders_process_checklist.js, app/models/process_checklist.js, app/routes/orders/order_types.js, app/services/processing-checklist.js, app/styles/templates/orders/_detail.scss, app/templates/orders/order_types.hbs, config/environment.js, tests/acceptance/order-details-appointment-info-test.js
https://jira.crossroads.org.hk/browse/GCW-2366
This PR relates to the 'Checklist' at the bottom of the logistics tab
=> Logistics tab : process checklist

app/components/order-inline-number-input.js, app/locales/en/translations.coffee, app/locales/zh-tw/translations.coffee, app/styles/templates/orders/_detail.scss, app/templates/orders/client_summary.hbs
Hi Team,
This PR is regarding adding validation for People Helped input in Summary tab.
Thanks
=> FIX: validation added for people helped in summary tab

app/components/order-inline-number-input.js, app/locales/en/translations.coffee, app/locales/zh-tw/translations.coffee, app/styles/templates/orders/_detail.scss, app/templates/orders/client_summary.hbs
Reverts crossroads/stock.goodcity#396
=> Revert "FIX: validation added for people helped in summary tab"

app/controllers/order/request_purpose.js
Hi Team,
This PR sorts districts alphabetically.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2439
Please review
=>  GCW:2439 Sorted district selection

app/components/variable-height-textarea.js, app/styles/templates/orders/_messages.scss
=> GCW-2425 fix chat issues

app/components/order-inline-number-input.js, app/locales/en/translations.coffee, app/locales/zh-tw/translations.coffee, app/styles/templates/orders/_detail.scss, app/templates/orders/client_summary.hbs
Hi Team,
This PR is regarding adding validation for People Helped input in Summary tab.
Thanks
=> FIX:  Validation for people helped in order summary

app/controllers/orders/conversation.js, app/controllers/orders/detail.js, app/controllers/subscription.js, app/models/designation.js, app/routes/orders/conversation.js, app/services/messages.js, app/styles/templates/orders/_index.scss, app/styles/templates/orders/_messages.scss, app/templates/orders/_order_tabs.hbs, app/templates/orders/order_block.hbs, app/templates/orders/unread_message_bubble.hbs
Hello Team this PR is for read unread tracking of messages.
Please review.
=> GCW-2414 read unread tracking of messages

app/styles/_appointment_details.scss, app/styles/_client_information.scss, app/styles/_request_purpose.scss, app/templates/order/appointment_details.hbs, app/templates/order/booking_success.hbs, app/templates/order/client_information.hbs, app/templates/order/request_purpose.hbs
Hi Team,
This PR is for adding validation on Select District and Select date on appointment page during Appointment booking process. And few CSS fixes mentioned on ticket GCW-2363. 
Thanks.
=> validation added for select-district and select date in Appointment Booking

app/styles/templates/components/_add_request.scss
Hi Team,
It fixes issue:  Dividing line between requests on booking form is wrong	
Edit Comment
Please review.
Thanks.
=> fix dividing line issue on goods-details page for order creation

app/controllers/order/search_users.js
Hello team, 
This PR allows user search the users even for 1 character.
=> GCW-2480 search user improvements

app/components/focus-textfield.js, app/controllers/search_module.js
Hi team this PR improves the organisations search.
- You can provide search terms longer than 25 characters
- You can include brackets in search terms
=> GCW-2481 improve organisation search

app/controllers/notifications.js, app/styles/templates/orders/_messages.scss, app/templates/notifications.hbs
Hello team this PR fixes the issues for blank notification on stock app.
main changes 
https://github.com/crossroads/stock.goodcity/pull/413/files#diff-1616934d9aeb74b7bbf71eff7a6ed2a2R31
https://github.com/crossroads/stock.goodcity/pull/413/files#diff-d9a8e6f8851e76cab05b106d305d825dR8
https://github.com/crossroads/stock.goodcity/pull/413/files#diff-31a61ce2fb36709b87beea82d00933bfR92
Screen shot for notification
=> GCW-2475 fix blank notification issue

app/templates/orders/_orders_back_link_path.hbs
Hi Team
This PR fixes backlink unresponsive issue for order detail screen
Jira tickets: https://jira.crossroads.org.hk/browse/GCW-2359, https://jira.crossroads.org.hk/browse/GCW-2322
Please review.
=> GCW:2359 backlink unresponsive fix

app/templates/sticky_footer.hbs, tests/acceptance/add-new-item-to-inventory-test.js
Hi Team,
This PR contains fix for iTunes: GoTo not available.
I've just commented the code in case we want to enable this feature in future.
Please review.
Thanks
=>  Itunes Fix- goto not available

app/components/designate-form.js, app/controllers/orders/items.js, app/locales/en/translations.coffee, app/locales/zh-tw/translations.coffee, app/models/item.js, app/routes/items/search_order.js, app/styles/templates/components/_designate_form.scss, app/templates/components/designate-form.hbs, app/templates/components/item-options-list.hbs
Hi Team,
This is PR for ticket GCW-2468- Allow Redesignated for designated and dispatch items. Please review the PR and let me know if any change is required.
Thanks.
=> GCW-2438 allow redesignate designated item

app/controllers/items/partial_undesignate.js, tests/acceptance/partial-undesignate-test.js
Hello team, 
This PR restricts user to partial dispatch if order is not processed.
Please review and comment
Thanks.
=> GCW-2394 restrict partial dispatch

app/components/designate-form.js, app/routes/items/search_order.js, app/templates/components/item-options-list.hbs
Hi Team,
This is fix for Multi quantity set appearance during designating item from Item Screen. And also managing undesignating quantity from Ember side instead of API side.
Thanks
=> FIX=> issue for multi-set item appearance during designation

app/models/item.js
Hi Team,
This is fix for ticket GCW-2525- location not getting updated after undispatching item on orders page. (https://jira.crossroads.org.hk/browse/GCW-2525).
Please review the PR and let me know if any change is required. 
Thans
=> GCW-2525- Add location computed property to detect location change

app/styles/_search.scss, app/styles/templates/orders/_index.scss
Hi team please review this PR for some misalignment issues on stock app.
Thanks
=> GCW-2309 fix css issues on stock

app/controllers/order/search_users.js, app/routes/order/search_users.js
Hi Team,
This PR is for clearing search text on changing page from search_users page during order creation. Please review the PR and let me know if any change is required.
Thanks
=> GCW-2429-User search keeps text, but the results are not correct

app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/models/organisations_user.js, app/models/user.js, app/templates/orders/contact_summary.hbs, tests/acceptance/order-organisation-and-contact-test.js, tests/factories/organisations_user.js
Hi Team,
This PR adds preferred contact number on the summary tab of the order.
Please review.
Thanks.
=> Gcw 2535 add preferred contact number to summary tab

app/routes/items/index.js, tests/acceptance/add-new-item-to-inventory-test.js
Hello team this PR fixes the item index search disappearing.
Thanks
=> GCW-2357 Fix item result dissappearing

app/locales/en/translations.coffee, app/locales/zh-tw/translations.coffee, package.json
- Added missing translation for preferred contact number
=> #April2019Release2: added missing translations

app/locales/en/translations.js, app/locales/zh-tw/translations.js
Add missing translations for redesignate
=> Add missing translations to redesignate

app/locales/en/translations.js, app/locales/zh-tw/translations.js
Hello team, 
Please review this PR for missing translations reported by Tim on GCW-2443
Thanks.
=> GCW-2443 fix issues reported by tim for missing translations

.circleci/config.yml, app/controllers/index.js, app/controllers/orders/index.js, app/routes/orders/index.js, app/templates/orders/index.hbs, package.json, tests/acceptance/dashboard-test.js, tests/acceptance/order-filters-time-test.js, tests/controller/order-index-test.js, yarn.lock
Hi Team, this is for adding Infinite scroll on orders search pages(https://jira.crossroads.org.hk/browse/GCW-2555).
Thanks.
=> GCW-2555-Add Infinite scroll on Orders search page

app/locales/en/translations.js, app/locales/zh-tw/translations.js
Issue link:
https://jira.crossroads.org.hk/browse/GCW-2443?focusedCommentId=34120&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-34120
=> Minor translation issue fix

app/controllers/orders/detail.js
Hi Team,
This PR removes the necessity of a process checklist completion to finish processing.
Change is only at : https://github.com/crossroads/stock.goodcity/compare/remove-validation-for-process-checklist-to-finish-processing#diff-8ab2a29690e6c67f18803ab795f4b57aR239
Please review.
Thanks.
=> remove validation of process checklist to finish processing

app/controllers/orders/detail.js, package.json
Hi Team,
It removes validation of process checklist to finish processing.
Please review.
Thanks
=> #May2019Release2

app/components/item-filter-buttons.js, app/components/order-filter-buttons.js, app/controllers/items/index.js, app/controllers/orders/index.js, app/controllers/search_module.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/routes/items/index.js, app/routes/orders/index.js, app/services/filter-service.js, app/styles/_filters.scss, app/templates/components/item-filter-buttons.hbs, app/templates/components/order-filter-buttons.hbs, tests/acceptance/order-filters-time-test.js, tests/acceptance/order-search-list-test.js, tests/factories/goodcity_request.js
This PR adds a little cross next to each filter button, allowing us to clear them without opening the actual page :
=> Filter buttons:  Clear filters

app/routes/items/new.js
Hi team,
This is a first fix for the broken images. We know for a fact it'll fix some of the problems, but we don't know if it'll fix everything.
This whole page is pretty flawed, so it might still be possible to break it from here. The big question is whether another part of the app is also responsible for the broken images.
We also found cloudinary has a restore function, so I will write a script to try and restore as many of the images that were deleted as possible
FYI, I only added this line `controller.set("imageKeys", "");` , the rest is prettier
=> FIX: images from previous items were not being cleared

app/templates/components/item-options-list.hbs
Hi Team, 
This is fix for adding undispatch options on Items search page. Please review the PR and let me know if any change is required.
Thanks
=> FIX=> add undispatch options on item search page

app/controllers/orders/detail.js, app/models/orders_process_checklist.js, app/services/processing-checklist.js
This is a temporary fix, we will work to move the fix in goodcity-lib afterwards.
We need to release ASAP as this is a blocker for the team
=> FIX broken process list due to headers not being sent

app/templates/orders/client_summary.hbs
We need to display request purpose for online order as well on stock app.
This PR contains changes for that. Please review 
Thanks.
=> GCW-2590 show request purpose on online orders also

app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/templates/order/_user_details.hbs, app/templates/orders/contact_summary.hbs
Hi Team,
This PR is for JIRA ticket GCW-2575- Bug related to preferred phone number and layout bug. Please review the PR and let me know if any change is required.
Thanks
=> GCW-2575-Stock - Preferred phone number not displayed on order confirmation page & layout bug

app/components/designate-form.js, app/components/item-options.js
Hi Team,
This PR is for JIRA ticket GCW-2577 (https://jira.crossroads.org.hk/browse/GCW-2577). I have added change for updating cancelled orders package in orders.
=> GCW- 2577- updating cancelled Orders Packages

app/controllers/orders/items.js
Hi Team,
This PR is for restricting multi quantity item search on Order Items Search page. Please review the PR and let me know if any change is required.
Thanks
=> FIX=> For restricting multi quantity item search on Order Items Search

Rakefile, cordova/config.xml
Hi Team,
This PR downgrades push plugin version for ios as the newer version has an issue with ios. We can upgrade it for ios later once they fix it.
https://github.com/phonegap/phonegap-plugin-push/issues/2222
Please review.
Thanks.
=> ios push notifications fix

package.json, yarn.lock
Hi Team,
This PR fixes vulnerability mentioned in alerts of this repo.
Please review.
Thanks.
=> Vulnerability fixes

app/locales/zh-tw/translations.js, app/styles/templates/components/_item_options_list.scss
Hi Team,
This PR is for css fix for icon misalignment. I've also added missing Chinese translation for `total_requests`. Please review the PR.
Thanks
=> GCW-2640- Undispatch icon misalignment

app/controllers/authenticate.js, app/services/auth-service.js, tests/acceptance/login-test.js, tests/unit/model/user-test.js
Hi, this PR fixes an issue that @namrataukirde found yesterday.
That being: The preload routine of Stock does not run when a user logs in, it is only run if the user was previously logged in before and restores the session.
The reason this hasn't exploded before, is because the records that need to be preloaded usually arrive as dependencies of other requests. Also some pages load the data themselves in routes.
Changes:
- Run the preload after login
- Some code cleanup of things I stumbled upon
=> Preload after login

app/components/designate-form.js
Hi Team, 
This PR is for ticket GCW-2653-redirect to orders instead of items index on assigning Item to order. I have added the redirection url. Please review the PR and let me know if any change is required. 
Thanks
=> GCW- 2653- redirect to orders instead of items index on assigning Item to order.

app/app.js
Hi Team,
Fixes deprecation warning: https://deprecations.emberjs.com/v2.x/#toc_ember-model_factory_injections-removed
Please review.
Thanks.
=> Fix MODEL_FACTORY_INJECTIONS deprecation

app/controllers/orders/order_types.js
Hi Team,
This PR is for sorting of District locations in Alphabetic order. Please review the PR and let me know if any change is required. 
**Change** : https://github.com/crossroads/stock.goodcity/pull/492/files#diff-2adf69d324e6d165ad7d956cee639ea6R140
=> GCW-2508- District selection in logistic tab is not in alphabetical order.

app/controllers/orders/detail.js
Hi Team,
I've added process checklist check for transitioning to `dispatching` state. Please review the PR and let me know if any change is required. 
Thanks
=> GCW-2441- Restrict Dispatching state if process checklist is unchecked.

app/routes/application.js
Render error messages coming from the API.
=> GCW-2763 handle errors graciously

app/controllers/users/new.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/styles/_search.scss, app/styles/templates/users/_new.scss, app/templates/organisations/users.hbs, app/templates/users/new.hbs
Hi Team,
This PR contains Addition of a preferred contact number field in the stock app for new user form,
It also contains the UI update for the same new user form.
Please review.
Thanks
=> Gcw 2752 add preferred contact number field on user form

app/styles/templates/items/_detail.scss, app/templates/items/_multiple_set_item_images.hbs, app/templates/items/_single_item_image.hbs, app/templates/items/detail.hbs
Very minor layout adjustments 👍
=> Items details : small css fixes

app/styles/templates/items/_new.scss
**Ticket link**
https://jira.crossroads.org.hk/browse/GCW-2826
**Bug**
This PR contains fixing the position on the Add image button which appears on new item creation page.
**Screenshot**
=> GCW-2826 Fixing the position of the add image button

app/controllers/items/detail.js, app/models/item.js, app/styles/templates/components/_toggle_switch.scss, app/templates/components/toggle-switch.hbs, app/templates/items/detail/tabs/location.hbs, app/templates/items/detail/tabs/publishing.hbs
Hi,
As mentioned during the call, we are disabling a couple buttons for now in order to release.
=> Disable move & publish button for multi-qty items

app/controllers/items/detail.js, app/templates/items/detail/tabs/publishing.hbs
I forgot to include this rule in the previous PR -- cc @namrataukirde
=> Fix: disable publish button if qty==0

app/components/item-filters.js, app/controllers/item_filters.js, app/controllers/items/index.js, app/controllers/orders/index.js, app/controllers/orders/items.js, app/mixins/search_resource.js, app/routes/items/index.js, app/routes/orders/items.js, app/templates/items/index.hbs, app/templates/orders/items.hbs, tests/acceptance/supervisor-user-footer-test.js, tests/controller/items/index-test.js
https://jira.crossroads.org.hk/browse/GCW-2807
FEATURE: Added infinite-scroll on Items and Orders item search page. Created `search` mixin to clean repeated codes.
=> GCW-2807-Add Infinite scroll on Items filters and search Item for Orders page.

app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/styles/_appointment_details.scss, app/styles/_request_purpose.scss, app/styles/_settings.scss, app/templates/order/appointment_details.hbs, app/templates/order/request_purpose.hbs
**Ticket link**
https://jira.crossroads.org.hk/browse/GCW-2457
**Bug**
Validation required for Select District on Request purpose page  and Date selection on Transport Page during Appointment booking.
ScreenShots
:
=> Gcw 2457 validation added for select district and select date

yarn.lock
https://jira.crossroads.org.hk/browse/GCW-2457
This PR contains the updated goodcity-lib latest changes yarn lock file
=> add latest goodcity-lib master commit hash to refer to latest changes

.circleci/config.yml
https://jira.crossroads.org.hk/browse/GCW-2809
It adds new p12 and provisioning profiles for production.
Please Review.
Thanks.
=> GCW-2809 add new p12 and provisioning profile

.circleci/config.yml, package.json
Hi Team,
This PR contains a new p12 and provisioning profile.
Please review.
Thanks.
=> #October2019Release1

app/components/dropdown-search.js, app/constants/additional-fields.js, app/controllers/items/detail.js, app/controllers/items/new.js, app/templates/components/dropdown-search.hbs, app/templates/items/detail/tabs/info.hbs
Changes includes:
* Refactored app/components/dropdown-search.js components. 
* Removed logs and debugger
* UI indentations.
* Removed Additional-fields service and moved its hard coded data to constants folder.
**Note**: There are still changes but we can encounter it in subsequent work.
=> Gcw 2804 additional fields ui with details page refactoring

app/controllers/users/new.js
BUG: Fixes error displaying on user creation from stock app.
User creation from stock app
=> GCW-2838 fix user creation error handling

app/styles/templates/items/_detail.scss, app/styles/templates/items/_new.scss
https://jira.crossroads.org.hk/browse/GCW-2804
This PR contains setting the width of input field and dropdown to full width on mobile devices and some css fixes
=> Gcw 2804 responsive input fields dropdown

app/styles/templates/components/goodcity/_orders_package_block.scss, app/templates/components/goodcity/orders-package-block.hbs
https://jira.crossroads.org.hk/browse/GCW-2779
Quick CSS rule to prevent text from overflowing
=> Prevent organisation name overflow

app/components/additinal-fields-input.js, app/components/dropdown-search.js, app/controllers/items/detail.js, app/controllers/items/new.js, app/mixins/fetch_package_detail.js, app/mixins/grades_option.js, app/mixins/search_resource.js, app/models/lookup.js, app/services/insert-fixed-option.js, app/services/subform-detail-service.js, app/styles/templates/items/_detail.scss, app/styles/templates/items/_new.scss, app/templates/items/detail/tabs/info.hbs, config/environment.js
FEATURE: Specify feature name
NOTE: Give a description of what this PR does. If it fixes any bug, specify cause of an issue and approach/solution added to fix that issue.
NOTE: List any impacted areas (e.g. Dashboard > My Active Offers > scheduled )
NOTE: Attach screeenshots if PR contains any UI changes
Note: Specify mockup link
NOTE: If these changes are related to some existing PR or fixes any issue from existing PR changes, specify PR links.
NOTE: IF there is any conversation happened for current changes in any of the slack channel, mention the slack message link.
=> Gcw 2804 final code refactoring

app/mixins/search_resource.js
https://jira.crossroads.org.hk/browse/GCW-2807
BUG:  On Orders > Item search page on text change , search was not tirggering. 
Also, on removing all text at once was not triggering search text query. It has been fixed.
=> FIX=> Infinite Scroll issue fix on Orders > items search page

app/components/dropdown-search.js, app/controllers/items/new.js, app/mixins/search_option.js, app/routes/items/new.js, app/templates/components/dropdown-search.hbs, app/templates/items/_additional_fields.hbs
FEATURE: Specify feature name
NOTE: Give a description of what this PR does. If it fixes any bug, specify cause of an issue and approach/solution added to fix that issue.
NOTE: List any impacted areas (e.g. Dashboard > My Active Offers > scheduled )
NOTE: Attach screeenshots if PR contains any UI changes
Note: Specify mockup link
NOTE: If these changes are related to some existing PR or fixes any issue from existing PR changes, specify PR links.
NOTE: IF there is any conversation happened for current changes in any of the slack channel, mention the slack message link.
=> GCW-2804 fix initial testing comments

app/controllers/items/detail.js, app/controllers/items/new.js, app/mixins/fetch_package_detail.js, app/services/subform-detail-service.js
FEATURE: Specify feature name
NOTE: Give a description of what this PR does. If it fixes any bug, specify cause of an issue and approach/solution added to fix that issue.
NOTE: List any impacted areas (e.g. Dashboard > My Active Offers > scheduled )
NOTE: Attach screeenshots if PR contains any UI changes
Note: Specify mockup link
NOTE: If these changes are related to some existing PR or fixes any issue from existing PR changes, specify PR links.
NOTE: IF there is any conversation happened for current changes in any of the slack channel, mention the slack message link.
=> GCW 2804 code climate issue feature

.circleci/config.yml, app/controllers/items/detail.js
https://jira.crossroads.org.hk/browse/GCW-2804
This PR removes the duplicate computed property 'tabName' from detail.js file as it shows error on IE11
=> GCW-2804 removed duplicate computed property

app/constants/additional-fields.js, app/styles/templates/items/_new.scss
https://jira.crossroads.org.hk/browse/GCW-2812
Bug: the PR contains uppercasing the Labels CPU, RAM, LAN, USB, and also includes reducing the size of text on input fields and drop down options on mobile devices.
Please review.
Thanks.
=> GCW-2804 css issues fixed

.circleci/config.yml, app/components/focus-textfield.js
BUG: On refresh something went wrong error popsup during PackageType Selection. 
Package Type selection during Package creation process.
Please review this PR and let me know if any change is required. 
Thanks.
=> FIX=> On refresh something went wrong error popsup during PackageType Selection.

app/controllers/items/new.js, app/models/item.js, app/routes/application.js
https://jira.crossroads.org.hk/browse/GCW-2881
BUG: If there is any issue in the item form, or subform, it throws an error. After fixing the data and resubmitting, it gives remove node issue, This PR fixes that remove node issue. 
Along with that, it also fixes some code, and make it better to understand now. 
Item Creation on stock app. Stockit Item sync.
https://github.com/crossroads/api.goodcity/pull/861
=> GCW-2881 inventory number already exists fix

app/styles/templates/_appointments.scss
https://jira.crossroads.org.hk/browse/GCW-2312
BUG: 
Manage appointment quotas screen UI broken(Mobile Screen), on one-plus-6 screen.
Please review 
Thanks
=> GCW-2312 fixed broken quotes page on one plus

app/components/add-request.js, app/components/designate-form.js, app/controllers/orders/add_request.js, app/controllers/orders/search_code.js, app/controllers/search_code.js, app/mixins/async.js, app/styles/templates/components/goodcity/_orders_package_block.scss, app/templates/components/designate-form.hbs, app/templates/components/goodcity/orders-package-block.hbs, app/templates/orders/_items_list_tabs.hbs, app/templates/orders/items.hbs, app/templates/orders/requested_items.hbs, tests/acceptance/goodcity-request-test.js
Fix of some navigation issues which cause an infinite loop between 2 pages
for requests: order details <-> search_code
and for items: order details <-> items search
This fixes that.
Note: the `designate-form` is going to be deleted in upcoming changes, not worth spending too much time on this file
=> Fix backlink issues on orders page

app/templates/items/detail/tabs/info.hbs
removal of duplicate code in `info.hbs`
=> remove duplicate code

app/controllers/items/new.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/models/location.js, app/models/printer.js, app/models/user.js, app/routes/items/new.js, app/services/printer-service.js, app/services/session.js, app/styles/templates/items/_new.scss, app/templates/items/new.hbs, config/environment.js, tests/unit/model/user-test.js
Ticket Link:
https://jira.crossroads.org.hk/browse/GCW-2853
What does this PR do?
FEATURE: Add a "Printer" single select control at the bottom right of the create form (in both admin and stock apps)
Please review
Thanks.
=> GCW-2853 UI for printer dropdown ready

app/services/printer-service.js, tests/acceptance/add-new-item-to-inventory-test.js, tests/acceptance/login-test.js
Ticket link:
https://jira.crossroads.org.hk/browse/GCW-2853
This PR temporarily removes broken test cases and adds sort by id to printer
Thanks
=> Gcw 2853 commenting test cases

app/styles/templates/items/_new.scss, app/templates/items/new.hbs, tests/acceptance/add-new-item-to-inventory-test.js, tests/acceptance/login-test.js
https://jira.crossroads.org.hk/browse/GCW-2853
This PR fixes the css and ui issues for printer dropdown and temporarily comments the the broken test cases
=> Gcw 2853 printer feature css fixes

Gemfile.lock
Hi Team,
This PR fixes excon vulnerability. Please review.
Thanks.
=> fix excon vulnerability

config/environment.js
FEATURE: Specify feature name
NOTE: Give a description of what this PR does. If it fixes any bug, specify cause of an issue and approach/solution added to fix that issue.
NOTE: List any impacted areas (e.g. Dashboard > My Active Offers > scheduled )
NOTE: Attach screeenshots if PR contains any UI changes
Note: Specify mockup link
NOTE: If these changes are related to some existing PR or fixes any issue from existing PR changes, specify PR links.
NOTE: IF there is any conversation happened for current changes in any of the slack channel, mention the slack message link.
=> remove storage-type from preload

app/styles/templates/items/_new.scss, app/templates/items/new.hbs
https://jira.crossroads.org.hk/browse/GCW-2872
BUG: 
This PR solves the bug of the validation message for the Size fields that covers part of the size field.
Screenshots
Please review:
=> GCW-2872 input field issue due to validation error solved

app/routes/items/new.js, app/services/session.js, package.json
Bump package version and resolve conflicts
=> Resolve live master conflicts

app/routes/items/new.js
https://jira.crossroads.org.hk/browse/GCW-2940
Clears weight and pieces fields on the new form
=> GCW-2940 fix weight and pieces not getting cleared on new form

.circleci/config.yml, .gitignore, README.md, app/components/goodcity/orders-package-block.js, app/components/let-alias.js, app/components/toggle-switch.js, app/controllers/goodcity_controller.js, app/controllers/items/index.js, app/controllers/orders/index.js, app/controllers/orders/items.js, app/controllers/orders/order_types.js, app/helpers/toggle.js, app/mixins/async.js, app/mixins/search_resource.js, app/models/item.js, app/routes/items/detail.js, app/services/api-base-service.js, app/services/designation-service.js, app/services/filter-service.js, app/services/location-service.js, app/services/settings.js, app/utils/cache.js, jsdoc.conf.json, package.json, yarn.lock
Hey team, 
I've been doing this in parallel of my task, I've extracted it into its own branch for you to test and let me know what you think.
The idea is to use JSDOC comments to keep track of everything. A lot of them were pre-existing so overall it was pretty easy to just tweak them a bit to get a decent setup.
Note: I've only documented the app partially here and there to get a feel for it.
Testing:
```bash
$> git fetch && git checkout jsdoc
$> yarn install  # to add the jsdoc dependency (node >= 8.15)
$> yarn document # generates a 'documentation' folder
$> open documentation/index.html # view the documentation in your browser
```
Questions in mind:
If you guys like this idea we can merge it, otherwise we can just discard the PR
=> Discussion: Adding JSDoc

package.json
Hi team
This PR contains increasing the app version in package.json file.
Please review.
=> Bump app version to 0.18.1

app/components/goodcity/add-item-overlay.js, app/templates/components/goodcity/add-item-overlay.hbs
Hi,
This PR contains getting the total sum of values in the input fields and set it on the MOVE button.
Thanks.
=> GCW-2859 set the total on move button based on the input field values

app/components/cancel-order.js, app/controllers/items/select_code.js, app/helpers/back-action.js, config/environment.js
More backlink fixes for ticket GCW-2904:
Change: Switch from `transitionTo` to `history.back()`
=> Fix for GCW-2904 (part 2)

app/components/goodcity/add-item-overlay.js, app/services/package-service.js, app/templates/components/contained-package.hbs
Hot master fix. 
Overlay is getting closed before the resolution of the response.
This PR fixes that issue.
=> GCW-2859 overlay getting closed before the response is coming

.circleci/config.yml, app/components/contained-package.js, app/controllers/items/detail.js, app/models/item.js, app/templates/components/contained-package.hbs
https://jira.crossroads.org.hk/browse/GCW-2859
**Fixes this bug:** 
https://jira.crossroads.org.hk/browse/GCW-2859?focusedCommentId=37131&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-37131
=> Gcw 2859 check issues related to contained packge removal

app/controllers/orders/detail.js, app/templates/orders/_items_list_tabs.hbs, app/templates/orders/_order_tabs.hbs
https://jira.crossroads.org.hk/browse/GCW-3007?focusedCommentId=37119&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-37119
FEATURE: Fix Comments
NOTE: Subtabs under Goods category i.e.., Active and Request are now getting highlighted.
NOTE: Recent Order>Click on any order>Goods>Active or Request
=> GCW-3007 Subtabs Under Goods category are now getting highlighted when selected

app/controllers/items/new.js
https://jira.crossroads.org.hk/browse/GCW-3039
Opens the barcode scanner and doesn't crashes at new items creation
BUG:barcode scanner on new item creation breaks.
NOTE: It had problem with the **this** structure, which was resolved
Change of scoping of **this** in checkPermissionAndScan()  method
=> GCW-3039 Scanning Issue while creating new items is resolved

app/components/goodcity/item-search-overlay.js, app/controllers/items/detail.js, app/routes/items/detail.js, app/templates/components/goodcity/item-search-overlay.hbs, app/templates/items/detail/tabs/storage_content.hbs
Commenting out scanner changes and moving it to separate ticket as the scanner is breaking the whole feature.
Thanks
=> GCW_2859 commenting out scanner changes and move it to a separate ticket

app/components/contained-package.js, app/controllers/items/detail.js, app/templates/components/contained-package.hbs
https://jira.crossroads.org.hk/browse/GCW-3044
FEATURE: Disables the ability to remove items from a box/pallet if box is dispatched.
=> GCW-3044 disable remove button for added items

app/controllers/items/detail.js
https://jira.crossroads.org.hk/browse/GCW-3043
FEATURE: Disable the ability of user to publish a box/pallet.
=> GCW-3043 dont allow box/pallet to publish

app/components/goodcity/add-item-overlay.js
GCW-2859
BUG: Fixes a bug where sometimes, added item is not rendered on the box content, was required to refresh the page.
=> Gcw 2859 fix item not rendering on adding error

app/controllers/orders/detail.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/models/designation.js, app/styles/templates/orders/_detail.scss, app/templates/orders/_cancel_message_popup.hbs, app/templates/orders/_order_status_bar.hbs
https://jira.crossroads.org.hk/browse/GCW-2931
FEATURE: 
1. Added cancel reason text for all cancellation reason type. 
2. Added 180 character limitation for reason.
3. Also added character counter for cancellation reason length below text area.
Please review.
=> FIX=> Cancellation reason UI fixes

app/adapters/offer.js, app/components/goodcity/offers-search-overlay.js, app/components/offer-tag.js, app/components/scan-barcode-button.js, app/controllers/application.js, app/controllers/items/detail.js, app/controllers/items/new.js, app/models/company.js, app/models/item.js, app/models/offer.js, app/models/offers_package.js, app/routes/items/detail.js, app/serializers/item.js, app/services/offer-service.js, app/styles/app.scss, app/styles/templates/components/_offer_tags.scss, app/styles/templates/components/goodcity/_search_overlay.scss, app/styles/templates/items/_new.scss, app/templates/_global_components.hbs, app/templates/components/goodcity/offers-search-overlay.hbs, app/templates/components/offer-tag.hbs, app/templates/items/detail/tabs/_item_detail.hbs, app/templates/items/new.hbs
https://jira.crossroads.org.hk/browse/GCW-2863
FEATURE: Associates Offers to package.
https://xd.adobe.com/view/224f7314-f1c0-40b6-7d7a-929e616be6bb-547e/screen/c800238a-5200-4a8a-adea-39f2303e5832/Create-Item-Main-Form?x_product=xd-jiraserver/1.0
=> GCW-2863-Support packages to offer

app/components/goodcity/add-item-overlay.js, app/components/goodcity/item-search-overlay.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/models/item.js, app/models/packages_location.js, app/styles/templates/components/_offer_tags.scss, app/templates/components/goodcity/add-item-overlay.hbs, app/templates/items/detail/tabs/storage_content.hbs
GCW-2859 https://jira.crossroads.org.hk/browse/GCW-2859
This PR fixes the following issues:
1. Box should not be listed in item search while adding for a box
2. If item has qty 1, on click should add directly instead of showing the move overlay
3. Fix for: When an item or box is added to a box or pallet, error messages continually appear on the item or box page until the page is reloaded. ( async: true for packages locations was causing the issue )
=> GCW-2859 bug fixes and suggestions implementation

app/styles/templates/orders/_detail.scss, app/templates/orders/_cancel_message_popup.hbs
https://jira.crossroads.org.hk/browse/GCW-2931
This PR adds  `typed character/180` format for showing typed characters.
=> FIX=> cancellation reason count UI changes.

app/components/goodcity/add-item-overlay.js, app/components/goodcity/item-search-overlay.js
https://jira.crossroads.org.hk/browse/GCW-2859
Adds a loader when trying to add packages from multiple locations.
=> GCW-2859 add loader while adding items

app/components/goodcity/item-search-overlay.js
GCW-2859
Adds a loader for while adding singleton item to box.
=> GCW-2859 Add loader while adding singleton item to box

app/components/goodcity/item-search-overlay.js, app/controllers/items/detail.js, app/styles/templates/items/detail/_storage_content.scss, app/templates/components/goodcity/item-search-overlay.hbs, app/templates/items/detail/tabs/storage_content.hbs
https://jira.crossroads.org.hk/browse/GCW-3041
FEATURE: Adds scanner feature to box/pallet 
Adds Scanner button to component as well as items route of box /pallet.
Update in UI 
Screenshots of the change in UI:
=> Gcw-3041 scanning feature for adding items to box and pallet fix

app/constants/additional-fields.js, app/controllers/items/new.js
https://jira.crossroads.org.hk/browse/GCW-3048
Renames some labels on the computer subform
=> GCW-3048 computer subform improvements

app/components/goodcity/item-search-overlay.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/templates/components/goodcity/item-search-overlay.hbs
GCW-2859
FIX: Limitation for cached searched items. 
Force the user to type in for searching.
=> GCW-2859 type in to search as cached results are causing issues

app/components/goodcity/offers-search-overlay.js, app/templates/components/goodcity/offers-search-overlay.hbs
Fix clear search text issue on offer search overlay.
=> Clear search on offer search overlay

app/controllers/orders/detail.js, app/templates/orders/_cancel_message_popup.hbs, app/templates/orders/_order_status_bar.hbs
https://jira.crossroads.org.hk/browse/GCW-3037
FEATURE: Clicking on cancel reason should open up popup to edit the cancellation reason.
=> GCW-3037 make cancellation reason editable

app/controllers/orders/detail.js, app/templates/orders/_cancel_message_popup.hbs
https://jira.crossroads.org.hk/browse/GCW-3037
Remaining char count issues fix
=> GCW-3037-fix-cancellation-reason-remaining-count

package.json
Bump App Version
please review this PR.
=> Bump App Version

app/mixins/fetch_package_detail.js
https://jira.crossroads.org.hk/browse/GCW-3063
Sort content of subform dropdowns.
- Item creation form screen
- Item details screen
=> GCW-3063- Sort computer subform dropdown attributes in ascending order

app/controllers/orders/detail.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/templates/orders/_cancel_message_popup.hbs
https://jira.crossroads.org.hk/browse/GCW-3037
Fixes the layout of cancellation popup.
=> GCW-3037 Improvements in layout of cancellation reason popup

package.json
Bump package version for release.
=> Bump package json

app/styles/templates/items/_index.scss, app/templates/items/index.hbs
https://jira.crossroads.org.hk/browse/GCW-3045
BUG: Fix the ui issue specified in the comment
jira.crossroads.org.hk/browse/GCW-3045?focusedCommentId=37444&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-37444
https://jira.crossroads.org.hk/browse/GCW-3045
=> GCW-3045-Add inventoryButton is now clickable from every point

app/controllers/orders/detail.js
Minor fix to observe connected cancellation reason and not the text box property.
=> change the observable property

app/components/goodcity/code-search-overlay.js, app/styles/templates/components/goodcity/_search_overlay.scss, app/templates/components/goodcity/offers-search-overlay.hbs
https://jira.crossroads.org.hk/browse/GCW-3071
BUG: Fixes the breaking of X button due to css issue
menu>create new item
https://jira.crossroads.org.hk/browse/GCW-3071?focusedCommentId=37638&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-37638
=> Breaking of X button at other overlay is fixed now

app/locales/zh-tw/translations.js
This PR adds translations for box pallet feature.
=> GCW-2859 add translations for box pallet story

app/components/goodcity/item-action-block.js, app/constants/item-actions.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/mixins/item_actions.js, app/templates/items/detail/tabs/_item_options.hbs
https://jira.crossroads.org.hk/browse/GCW-3087
Gain action for stock items.
=> GCW-3087 support gain action at items

app/controllers/orders/items.js, app/styles/_search.scss, app/templates/orders/items.hbs
https://jira.crossroads.org.hk/browse/GCW-3080
BUG: Scanner is working fine in orders/items page and the issue of x button is fixed
=> GCW-3080-Scanner button as well as X button is working now

app/styles/templates/items/detail/_publishing_tab.scss, app/templates/items/detail/tabs/_item_options.hbs
https://jira.crossroads.org.hk/browse/GCW-3036
Disable item options for zero quantity
=> GCW-3036 disable item options for zero quantity

app/styles/_client_information.scss, app/styles/_request_purpose.scss
https://jira.crossroads.org.hk/browse/GCW-2958
=> GCW-2958 fixed UI issues at client_information page

app/templates/items/new.hbs
https://jira.crossroads.org.hk/browse/GCW-3018
Only numbers between 0-9 are accepted and nothing else than that.
=> GCW-3018-Special characters are not allowed now in labels

app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/mixins/item_actions.js, app/styles/templates/items/detail/_publishing_tab.scss, app/styles/templates/orders/_detail.scss, app/templates/items/detail/tabs/_item_options.hbs
https://jira.crossroads.org.hk/browse/GCW-3087
fixed package gain-loss actions UI issues
- Avoid clicking of disabled options
- fixed missing translation at gain action form
- fixed quantity number input and its max accepted value
=> GCW-3087 fixed package gain-loss actions UI issues

app/templates/items/new.hbs, yarn.lock
https://jira.crossroads.org.hk/browse/GCW-3018
Upgrades goodcity.lib in yarn.lock file and changes in numeric input to accept value
=> Upgraded Yarn.lock

app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/router.js, app/routes/application.js, app/styles/templates/_index.scss
https://jira.crossroads.org.hk/browse/GCW-2588
handle invalid routes and invalid record fetching
**Invalid route:**
**Invalid Order:**
**Invalid Item:**
=> GCW-2588 handle invalid routes and invalid record fetching

app/components/goodcity/locations-search-overlay.js, app/mixins/item_actions.js, app/templates/components/goodcity/locations-search-overlay.hbs
https://jira.crossroads.org.hk/browse/GCW-3087
This PR fixes issue with a location search at gain action form.
=> GCW-3087 fixed location search at gain action

app/components/quantity-chooser.js, app/mixins/async.js, app/services/package-service.js, app/services/subscription.js
Changes:
* GCW-3086 Errors generated by live updates are sent to rollbar without any popup
* Fix: Split item popup doesn't show error message
=> GCW-3086 -  Silent live update errors

app/templates/components/package-summary-block.hbs
=> FIX=> icon according to storage type on new item layout

app/routes/orders/client_summary.js, package.json, tests/acceptance/purpose-test.js
This Release has fix for following ticket:
- Client name appears as 'undefined undefined' when a new order is created (GCW-3112)
=> Release[0.18.6] : Client name is undefined on client summary page

app/components/calendar-input.js, app/controllers/orders/detail.js, app/controllers/orders/order_types.js, config/environment.js
https://jira.crossroads.org.hk/browse/GCW-3113
Fixed issue with  populating schedule-date on logistics page
Solution: read and convert the dates using moment.js and hong-kong timezone.
=> GCW-3113 fixed populating schedule-date on logistic page

app/controllers/orders/order_types.js, app/models/orders_process_checklist.js, app/routes/authorize.js, app/routes/orders/order_types.js
Ticket Link:
https://jira.crossroads.org.hk/browse/GCW-3109
What does this PR do?
fixed fetching of orders_processing_checklists for orders
=> GCW-3109 fixed fetching of orders_processing_checklists for orders

app/controllers/app_menu_list.js
It fixes the error recieved while creating new orders
=> Fix of create new order breaking in stock app

.circleci/config.yml
https://jira.crossroads.org.hk/browse/GCW-3072
Uprgraded `xcode` version on CI script.
=> GCW-3072-iOS 13 SDK for all app builds

.circleci/config.yml
=> FIX=> Upgrade ruby image version for xcode 11

.circleci/config.yml
=> FIX=> Upgrade ruby image version for xcode 11 #696

app/helpers/back-action.js, app/templates/settings/appointments/manage_quotas.hbs
https://jira.crossroads.org.hk/browse/GCW-3084
fixed issue with backlinks
=> GCW-3084 fixed issue with backlinks

app/styles/templates/items/_detail.scss, app/styles/templates/items/_new.scss
https://jira.crossroads.org.hk/browse/GCW-3116
Currently the background of that widget is white with a light colored text on it. This is too hard for users to read. This PR changed the background to black.
=> GCW-3116 -  Make list-search form input easier to read

.circleci/config.yml
=> FIX=> fix ios live build because of chruby

app/components/beneficiary-inline-input.js, app/styles/templates/orders/_detail.scss, app/templates/orders/client_summary.hbs, tests/acceptance/purpose-test.js
https://jira.crossroads.org.hk/browse/GCW-3115
Creates separate editable field for the first and last names
=> GCW-3115 Editing the 'Client's Name' field in an order with spaces can cause some issues

app/routes/orders/client_summary.js
https://jira.crossroads.org.hk/browse/GCW-3122
Fixes the bug when client summary tab is visited after the beneficiary is deleted for the order
=> GCW-3122 Deleting Beneficiary Gives Error

app/controllers/items/detail.js, app/controllers/items/new.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/models/item.js, app/styles/_checkbox_styles.scss, app/templates/items/detail/tabs/_item_detail.hbs, app/templates/items/new.hbs
https://jira.crossroads.org.hk/browse/GCW-3119
Adds saleable field in creating and edit section of item
Linked PR: https://github.com/crossroads/api.goodcity/pull/973
=> GCW-3119 Add "Saleable" field to create / view / edit on packages

app/controllers/app_menu_list.js, app/controllers/order/request_purpose.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/templates/order/request_purpose.hbs
Fixed people Helped column in Create Orders page
=> Changes made to people benefited people

app/controllers/items/detail.js, app/mixins/async.js, app/services/package-service.js, app/styles/app.scss, app/styles/templates/components/_package_summary_block.scss, app/styles/templates/items/detail/_location_tab.scss, app/templates/components/goodcity/add-item-overlay.hbs, app/templates/components/package-summary-block.hbs, app/templates/items/detail.hbs, app/templates/items/detail/tabs/location.hbs, tests/acceptance/item-details-tabs-test.js
In the location tab of the Item's detail page, we list out the boxes it is contained in.
As shown here:
https://xd.adobe.com/view/224f7314-f1c0-40b6-7d7a-929e616be6bb-547e/screen/10440166-c9aa-4342-83ed-3e2b53973c86/?x_product=xd-jiraserver%2F1.0
=> GCW-3104 Parent boxes/pallets

app/styles/templates/items/_detail.scss, app/styles/templates/items/_new.scss
=> Fix=> Improve background color for dropdown of subform

app/components/sticky-footer.js, app/controllers/my_notifications.js, app/helpers/message-time.js, app/locales/en/translations.js, app/mixins/preload_data.js, app/router.js, app/routes/my_notifications.js, app/services/messages.js, app/styles/app.scss, app/styles/templates/_index.scss, app/styles/templates/_my_notifications.scss, app/templates/app_menu_list.hbs, app/templates/components/sticky-footer.hbs, app/templates/index.hbs, app/templates/items/index.hbs, app/templates/my_notifications.hbs, app/templates/orders/index.hbs, app/templates/search_organisation.hbs, app/templates/sticky_footer.hbs
https://jira.crossroads.org.hk/browse/GCW-3120
Messages Center to display a list of all unread messages. 
https://github.com/crossroads/api.goodcity/pull/977
=> GCW-3120 Message Center

app/components/date-picker.js, app/controllers/items/detail.js, app/controllers/items/new.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/models/code.js, app/models/item.js, app/styles/templates/items/_detail.scss, app/templates/items/detail/tabs/_item_detail.hbs, app/templates/items/new.hbs
https://jira.crossroads.org.hk/browse/GCW-3118
This PR adds `allow_expiry_date` on package_type model. According to its boolean value it displays `expirty_date` on package creation and its show page.
=> GCW-3118-Add "expiration date" field on some goods types

app/templates/components/package-summary-block.hbs, package.json
=> Release[0.18.9] GCW-3129 Publish status on package blocks

app/components/goodcity/code-search-overlay.js, app/helpers/highlight-substr.js, app/templates/components/goodcity/code-search-overlay.hbs
https://jira.crossroads.org.hk/browse/GCW-3128
This PR makes 3 letter package type searchable in Package Type search.
=> GCW-3128-Display 3 letter code & make searchable when choosing item types

app/components/package-summary-block.js, app/styles/templates/items/detail/_publishing_tab.scss, app/templates/components/package-summary-block.hbs, app/templates/items/detail/tabs/_item_options.hbs
Using the new package summary component in package-actions form.
=> use package-summary-block design in package-actions form

app/controllers/appointments.js
https://jira.crossroads.org.hk/browse/GCW-2910
fixed issue with creating special day appointment slots
=> GCW-2910 fixed issue with creating special day appointment slots

app/components/dropdown-search.js, app/controllers/items/new.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/services/settings.js, app/styles/templates/items/_new.scss, app/templates/items/_additional_fields.hbs, app/templates/items/new.hbs
https://jira.crossroads.org.hk/browse/GCW-3111
FEATURE:To duplicate creation of item
=> Gcw 3111 add duplicate item checkbox

app/templates/items/new.hbs, package.json
Regex on weight and pieces did not allow any zeroes. Moving this to live asap as the team is having issues creating items
=> Patch form validation new item

app/components/numeric-inline-input.js, app/constants/regex.js, app/controllers/items/detail.js, app/controllers/items/new.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/models/item.js, app/routes/items/detail.js, app/routes/items/new.js, app/services/package-service.js, app/styles/templates/items/_detail.scss, app/styles/templates/items/_new.scss, app/templates/items/detail/tabs/_item_detail.hbs, app/templates/items/new.hbs, yarn.lock
https://jira.crossroads.org.hk/browse/GCW-3127
Creates new field for value based on the grade of the package.
Stock > Create new Item
=> GCW-3127 Place overridden value on Stock item screen

app/controllers/items/new.js, app/templates/items/new.hbs, yarn.lock
Item valuation field was not accepting 0 value because of a flag and regex. This fixes the issue
=> Fix value field to accept zeros

app/controllers/items/new.js
Fix the bug of unable to add 0 as label count
=> Fixing zero value for print label

app/components/item-filters.js, app/templates/items/_state_filters.hbs
=> FIX => Make entire state checkbox clickable on Item filters.

app/controllers/items/new.js
jira.crossroads.org.hk/browse/GCW-3111?focusedCommentId=38402&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-38402
BUG: Model field was not getting duplicated fix
=> GCW-3111-Fixed bugs of model field not getting duplicated.

app/components/inline-select-list.js, app/components/numeric-inline-input.js, app/controllers/items/detail.js, app/routes/items/detail.js, app/styles/templates/items/_detail.scss, app/templates/items/detail/tabs/_item_detail.hbs
- Does the UI logic change in item_detail screen as mentioned in the standup call.
- Minor changes in the fetching of default_value_hk field in item_detail
=> GCW-3127 UI suggestions and detail screen default value logic changes

app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/models/item.js, app/models/storage-type.js, app/services/package-service.js, app/templates/items/sticky_footer.hbs
=> GCW-3101 Prevent boxes in sets

app/components/goodcity/orders-package-block.js, app/controllers/items/detail.js, app/styles/templates/items/_detail.scss, app/styles/templates/items/detail/_storage_content.scss, app/templates/components/contained-package.hbs, app/templates/items/sticky_footer.hbs
* CSS fixes for contained packages
* Hide action menu when clicking outside of it
=> Item Details: UI Adjustments

app/templates/authenticate.hbs
Fix for sms otp textbox not accepting 0
=> Fix for sms text box Breaking

app/components/focus-textfield.js, app/routes/index.js, app/templates/index.hbs
Quick fix for ticket [GCW-3160](https://jira.crossroads.org.hk/browse/GCW-3160)
I observed a different behaviour on my machine and on staging. But hopefully this will fix everything
=> GCW-3160 Fix dashboard order links

app/components/focus-textfield.js, app/routes/index.js, app/templates/authenticate.hbs, app/templates/index.hbs, package.json
=> [Release] 0.19.4 - GCW-3160 Fix dashboard order links

app/components/numeric-inline-input.js, app/components/numeric-inline-input.js.rej, app/controllers/items/detail.js, app/controllers/items/new.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/routes/items/detail.js, app/routes/items/new.js, app/templates/items/detail/tabs/_item_detail.hbs, app/templates/items/new.hbs, yarn.lock
https://jira.crossroads.org.hk/browse/GCW-3127
This fixes most of the issues mentioned in the ticket
=> GCW-3127 QA Fixes for valuation field

app/components/order-inline-textarea-input.js
https://jira.crossroads.org.hk/browse/GCW-2883
BUG: Previous Value was not getting set and hence the request was firing
https://github.com/crossroads/stock.goodcity/pull/761/files#diff-6deee1359b3882ccb90df1b389ce4de1R74
=> GCW-2883-Request fires when same data is kept and focussed out

app/components/item-description-textarea.js, app/components/offer-tag.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/styles/templates/components/_offer_tags.scss, app/styles/templates/items/_detail.scss, app/styles/templates/items/_new.scss, app/templates/components/donation-field.hbs, app/templates/components/offer-tag.hbs, app/templates/items/detail/tabs/_item_detail.hbs, app/templates/items/new.hbs, tests/acceptance/item-inline-edit-test.js, tests/acceptance/split-quantity-of-items-test.js
https://jira.crossroads.org.hk/browse/GCW-3155
FEATURE: Adds new layout to the item/details screen
Items -> Details
=> GCW-3155-Changes to add new layout to item/details screen

app/controllers/items/new.js
https://jira.crossroads.org.hk/browse/GCW-2870
fixed url update on updating donation field
=> GCW-2870 fixed url update on updating donation field

app/constants/saleable-options.js, app/controllers/items/detail.js, app/controllers/items/new.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/mixins/grades_option.js, app/models/item.js, app/models/restriction.js, app/routes/items/new.js, app/styles/templates/items/_detail.scss, app/templates/items/detail/tabs/_item_detail.hbs, app/templates/items/new.hbs, config/environment.js, tests/unit/model/item-test.js, tests/unit/model/packages-location-test.js
https://jira.crossroads.org.hk/browse/GCW-3153
This PR adds constraints, saleable and comment field in packages creation and details page.
=> GCW-3153-Add constraints restriction to packages

app/controllers/items/index.js
https://jira.crossroads.org.hk/browse/GCW-3171
FEATURE:  Cache `item` search results.
=> GCW-3177- cache search results of item search

app/controllers/orders/order_types.js, app/templates/orders/_order_status_bar.hbs, app/templates/orders/_order_tabs.hbs, app/templates/orders/active_items.hbs, app/templates/orders/order_types.hbs
https://jira.crossroads.org.hk/browse/GCW-3166
This PR restricts `draft` order in recently_used orders along with specs.
=> GCW-3166- restrict draft order in recent_orders

app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/styles/templates/items/_detail.scss, app/templates/items/detail/tabs/_item_detail.hbs
Changes made to item/details page as referred in the ss
=> Changes to items/detail page as per suggestion

app/styles/templates/items/_detail.scss
Changes the CSS of the Expiry Date
=> Changes in the css of expiry date

app/routes/application.js
https://jira.crossroads.org.hk/browse/GCW-3175
BUG: Error while logging out from two simultaneous windows tab
=> GCW-Fix for the unloadSession Error

app/controllers/items/new.js, app/models/item.js, app/templates/items/detail/tabs/_item_detail.hbs, app/templates/items/new.hbs
=> Add => Comment in Package model. #1025

app/components/display-package-code.js, app/styles/app.scss, app/styles/templates/components/_display_package_code.scss, app/styles/templates/items/_detail.scss, app/templates/components/display-package-code.hbs, app/templates/components/package-summary-block.hbs, app/templates/items/detail/tabs/_item_detail.hbs, tests/integration/components/display-package-code-test.js
https://jira.crossroads.org.hk/browse/GCW-3174
FEATURE: Separate Component for displaying code along with package-type
=> GCW- 3174 display code along with package type

app/components/calendar-input.js, app/components/date-picker.js, app/styles/templates/items/_detail.scss, app/styles/templates/items/_new.scss, app/templates/items/detail/tabs/_item_detail.hbs, app/templates/items/new.hbs
https://jira.crossroads.org.hk/browse/GCW-3173
This PR adds feature to select years from dropdown in datepicker instead of navigating through different months.
=> GCW- 3173-Item creation datepicker UX

app/components/item-description-textarea.js, app/components/request-description-textarea.js, app/styles/templates/items/_detail.scss, app/templates/items/detail/tabs/_item_detail.hbs
https://jira.crossroads.org.hk/browse/GCW-3183
Makes the field optional and added changes in component to make it  dynamic
https://github.com/crossroads/stock.goodcity/pull/776/files#diff-f946bdfa64a2d3937633ed9754cb9aecR11
=> GCW-3181 Made comment field optional

app/components/goodcity/add-item-overlay.js, app/components/package-summary-block.js, app/styles/templates/components/_package_summary_block.scss, app/templates/components/goodcity/add-item-overlay.hbs, app/templates/components/package-summary-block.hbs, app/templates/items/detail/_set_list.hbs
https://jira.crossroads.org.hk/browse/GCW-3184
Default image is added instead of test image from cloudinary
=> GCW-3184-Add default image for packages

app/styles/templates/_index.scss, app/templates/components/goodcity/locations-search-overlay.hbs
https://jira.crossroads.org.hk/browse/GCW-3191
BUG:  Text Cutoff fix
=> GCW-3191-Text Cutoff in location overlay fixed

app/components/variable-height-textarea.js
=> Fix rollbar error for nodename in contenteditable

app/components/variable-height-textarea.js, app/styles/_mentions.scss, package.json, yarn.lock
Fixes the errors in https://jira.crossroads.org.hk/browse/GCW-3167
=> Fix mentions UI errors

app/components/calendar-input.js, app/components/date-picker.js, app/controllers/items/detail.js, app/routes/items/new.js, app/templates/items/detail/tabs/_item_detail.hbs
Hi Team,
This PR fixes bug on date picker. 
- On opening the date-picker it is now selecting existing date value.
- Used same date-picker for both Item-new and item-details screen for uniformity.
- Made `calendar-input` workable for edit operation.
=> Fix datepicker bug

app/controllers/items/new.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/styles/templates/items/_new.scss, app/templates/items/new.hbs
https://jira.crossroads.org.hk/browse/GCW-3193
FEATURE: Added a success box which indicates success view of duplicate item
=> Pop-up Success box added

app/components/quantity-chooser.js, app/styles/_custom.scss, app/templates/components/quantity-chooser.hbs, app/templates/items/detail/_tabs.hbs, app/templates/items/sticky_footer.hbs, tests/acceptance/split-quantity-of-items-test.js
https://jira.crossroads.org.hk/browse/GCW-3192
FEATURE: Added split-items quantity to the sheet
=> GCW-3192-Split Quantity button added successfully

app/components/calendar-input.js, app/controllers/items/detail.js, app/models/item.js
=> Fix the Calendar Issue in Item Detail Page

app/serializers/application.js
https://jira.crossroads.org.hk/browse/GCW-3203
Fix the error in Client Information Page
Client Information
=> GCW-3203 Fix Client Information Page

app/controllers/items/detail.js
https://jira.crossroads.org.hk/browse/GCW-3194
Allow boxes & pallets to be published
Stock - Details Screen
=> GCW-3194 Adding Box Pallet Publish Option

app/adapters/item_action.js, app/constants/item-actions.js, app/controllers/items/history.js, app/helpers/format-display-value.js, app/helpers/item-action-icon.js, app/helpers/startcase-string.js, app/models/item.js, app/models/item_action.js, app/models/version.js, app/routes/items/history.js, app/serializers/item.js, app/styles/templates/items/_history.scss, app/templates/items/_action_version_header.hbs, app/templates/items/_edit_item_block.hbs, app/templates/items/_item_action_block.hbs, app/templates/items/history.hbs, app/templates/items/sticky_footer.hbs, package.json, yarn.lock
https://jira.crossroads.org.hk/browse/GCW-3185
FEATURE:  On history tab in Item it shows comprehensive history of `Actions` and `version` changes applied on Item.
=> GCW-3185- packages history

app/controllers/items/detail.js, app/templates/items/detail/_set_header.hbs
https://jira.crossroads.org.hk/browse/GCW-3189
Fixes invalid package type selection for box/pallet/set
Item detail screen
=> GCW-3189 User should not be able to change member of a set or a box/pallet to an invalid type

app/controllers/items/new.js
https://jira.crossroads.org.hk/browse/GCW-3194
Allow box and pallets to be published from create screen as well, which was missed in the earlier PR
=> GCW-3194 Allow box and pallets to be published

app/styles/_client_information.scss, app/styles/templates/components/_add_request.scss, app/styles/templates/items/_new.scss, app/styles/templates/orders/_request.scss, app/templates/components/appointment-add-request.hbs, app/templates/components/goodcity/orders-package-block.hbs, app/templates/components/order-add-request.hbs, app/templates/items/new.hbs, app/templates/order/_goods_detail.hbs
https://jira.crossroads.org.hk/browse/GCW-3174?focusedCommentId=39098&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-39098
Adds Package along with code and default package icons in all the remaining places in stock app
=> GCW-3174-Added Package along with code and default icon in all places

app/locales/en/translations.js, app/locales/zh-tw/translations.js
https://jira.crossroads.org.hk/browse/GCW-3228
Change Locale text
=> GCW-3228 Fix Locale Text

app/controllers/items/history.js, app/routes/items/history.js, app/services/organisation-service.js, app/services/package-service.js
This PR loads Item versions details separately instead of loading with Item association.
=> FIX => Loading versions in separate endpoint for package history.

app/locales/en/translations.js, app/locales/zh-tw/translations.js
https://jira.crossroads.org.hk/browse/GCW-3223
As in title
=> GCW-3228 Fix Labels

app/components/calendar-input.js, app/templates/items/detail/tabs/_item_detail.hbs
https://jira.crossroads.org.hk/browse/GCW-3222
Fixes the inconsistencies in Expiry Date
Item details screen
=> Gcw 3222 Fix Expiry Date

app/controllers/items/history.js, app/helpers/format-display-value.js, app/templates/items/_edit_item_block.hbs
This PR fix `saleable` property displayed as `-` for `Not selling` and `Not selling` value.
=> FIX=> Saleable not displaying properly in history.

app/controllers/items/detail.js, app/templates/items/detail/tabs/_item_detail.hbs
=> Fix Clear Date Issue

app/components/calendar-input.js, app/controllers/items/detail.js, app/controllers/items/history.js, app/helpers/format-display-value.js, app/templates/items/_edit_item_block.hbs, app/templates/items/detail/tabs/_item_detail.hbs, package.json
- Fix Expiry Date Issue
- Fix Saleable Field Issue
=> 22nd June Hotfix

app/styles/templates/items/detail/_publishing_tab.scss
https://jira.crossroads.org.hk/browse/GCW-3232
Fix the dropdown menu thats getting cut at the bottom by making it scrollable
=> GCW-3232 Fix Dropdown Display

app/controllers/authenticate.js
https://jira.crossroads.org.hk/browse/GCW-2834
BUG: If the wrong pin is entered before the correct one while logging ,the user won't be sent to the 'Home' page fix
=> GCW-2834-If the wrong pin is entered before the correct one while logging ,the user won't be sent to the 'Home' page fix

app/templates/authenticate.hbs
https://jira.crossroads.org.hk/browse/GCW-3214
BUG: Added numerical input to PIN input
=> GCW-3124-Added numerical imput to PIN

app/styles/templates/components/_message_box.scss, app/styles/templates/components/_toggle_switch.scss, app/styles/templates/components/goodcity/_designate_form.scss, app/styles/templates/items/detail/_publishing_tab.scss, app/styles/templates/orders/_index.scss, app/templates/components/goodcity/designate-form.hbs, app/templates/items/detail/tabs/publishing.hbs
https://jira.crossroads.org.hk/browse/GCW-3233
Fixes the inconsistencies in mobile device display
=> GCW- 3233 Fix modal dialogue for small devices

app/styles/templates/orders/_detail.scss
https://jira.crossroads.org.hk/browse/GCW-3195
BUG: Processing checkbox issue fixed
=> GCW-3195-Layout issues with processing checkbox fixed in the small size screens

app/components/goodcity/add-item-overlay.js
https://jira.crossroads.org.hk/browse/GCW-3218
reset package defaultaddablequantity on form close
=> GCW-3218 reset package defaultaddablequantity on form close

app/services/printer-service.js
https://jira.crossroads.org.hk/browse/GCW-3238
List printers in alphabetical order in drop-down. Added its change in printer-service.
=> GCW-3238- List printers in alphabetical order

app/styles/templates/_index.scss, app/styles/templates/items/detail/_publishing_tab.scss, app/templates/components/goodcity/orders-package-block.hbs, app/templates/items/detail/tabs/_item_options.hbs, app/templates/items/detail/tabs/publishing.hbs
https://jira.crossroads.org.hk/browse/GCW-3196
Fix QA reported issue in the ticket
=> GCW-3196 Fix Layout

app/styles/templates/items/_detail.scss
=> GCW-3196 Add footer height

app/controllers/items/new.js
https://jira.crossroads.org.hk/browse/GCW-2962
Display proper validations for size fields
Item creation
=> GCW-3205 Add size validation

app/models/user_profile.js
https://jira.crossroads.org.hk/browse/GCW-3213
BUG: Order Administrator can now view dashboard(home page) in stock app
=> GCW-3213-Order Administrator can now view dashboard

app/controllers/items/new.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/templates/items/new.hbs
https://jira.crossroads.org.hk/browse/GCW-3205
Adds proper validations for dimensions
Item creation
=> GCW-3205 Adding proper validations

app/controllers/items/detail.js, app/controllers/items/new.js
https://jira.crossroads.org.hk/browse/GCW-3219
Remove pieces input from box and pallet form
=> GCW-3219 Remove pieces input from box and pallet form

app/controllers/items/history.js, app/helpers/format-display-value.js, app/models/item.js, app/routes/items/history.js
https://jira.crossroads.org.hk/browse/GCW-3230
FEATURE: This PR displays subforms versions along with package versions in package history page.
=> GCW-3230- Adding subform versioning 

app/controllers/items/detail.js, app/styles/templates/components/_package_summary_block.scss
https://jira.crossroads.org.hk/browse/GCW-3235
BUG: Issues related to modal fixed
=> GCW-3235-Issues related to modal fixed

app/components/goodcity/item-search-overlay.js, app/controllers/stocktakes/detail.js, app/controllers/stocktakes/index.js, app/helpers/signed-number.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/mixins/async.js, app/models/stocktake.js, app/models/stocktake_revision.js, app/routes/stocktakes/detail.js, app/serializers/application.js, app/serializers/stocktake_revision.js, app/styles/_search.scss, app/styles/templates/stocktakes/_detail.scss, app/styles/templates/stocktakes/_index.scss, app/templates/items/detail/tabs/storage_content.hbs, app/templates/stocktakes/detail.hbs, app/templates/stocktakes/index.hbs
https://jira.crossroads.org.hk/browse/GCW-3209
Fixes issues addressed by Matt and Tim, including (but not limited to) :
- Responsive design bugs
- Packages with 0 quantity cannot be searched
- List scroll bug
- Show recorded diff on processed (closed) revisions
- Show date of closing next to state
- Fix serialisation issue which caused API bug
=> GCW-3209 Stocktake ui fixes

app/controllers/items/new.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/templates/items/new.hbs
https://jira.crossroads.org.hk/browse/GCW-2962
Adds an inline validation message for inventory number when its not auto generated and kept a blank value.
=> GCW-2962 Add inline message for Inventory Number

app/routes/items/detail.js, app/templates/items/sticky_footer.hbs
https://jira.crossroads.org.hk/browse/GCW-3245
disable make-set option for set items
=> GCW-3245 disable make-set option for set items

app/models/item.js
=> Fix => location getting null on updating items on details page.

app/controllers/items/detail.js
https://jira.crossroads.org.hk/browse/GCW-3241
BUG: Scanner fix for box and pallet
=> GCW-3241-Scanner fix for box and pallet

app/styles/templates/items/_detail.scss, app/templates/items/detail/tabs/_item_detail.hbs
https://jira.crossroads.org.hk/browse/GCW-3227
Fix Expiry Date Layout for small devices
=> GCW-3227 Fix Layout For Expiry Date

app/components/goodcity/add-item-overlay.js, app/controllers/items/detail.js
https://jira.crossroads.org.hk/browse/GCW-3240
BUG: Add item to box pallet break fix
=> GCW-3240-Add item to box pallet break fix

app/serializers/application.js, app/services/subscription.js
https://jira.crossroads.org.hk/browse/GCW-1605
This PR fixes live update issue with images
=> GCW-1605 fixed live update of images

app/controllers/items/detail.js, app/mixins/item_actions.js, app/styles/templates/items/detail/_publishing_tab.scss, app/templates/items/detail/tabs/_item_options.hbs, app/templates/items/sticky_footer.hbs
https://jira.crossroads.org.hk/browse/GCW-3207 
BUG: Wrong labels were displaying while gaining in box or pallet
=> GCW-3207-Wrong labels were displaying while gaining in box or pallet

app/models/user_profile.js, app/templates/manage_users.hbs
https://jira.crossroads.org.hk/browse/GCW-3279
hide user-create link when user don't have manage-user permission
=> GCW-3279 hide user-create link when user dont have manage-user permission

app/components/item-description-textarea.js, app/styles/templates/items/_detail.scss, app/templates/items/detail/tabs/_item_detail.hbs
https://jira.crossroads.org.hk/browse/GCW-3271
BUG: Error message when emptying item description field fix
=> GCW-3271-Error Message of send null from description text box is resolved

app/models/user_profile.js, app/routes/index.js, app/templates/index.hbs, tests/helpers/mock-utils.js
https://jira.crossroads.org.hk/browse/GCW-3212
Fixes the QA reported issue
=> GCW-3212 Fix stock fulfilment unable to view dashboard

app/routes/items/new.js, app/services/session.js, config/environment.js
https://jira.crossroads.org.hk/browse/GCW-3247
Fixes the error message while creating item.
=> GCW-3247 Fix Unexpected Error Message

app/models/printer.js, app/models/printers_user.js, app/models/user.js, app/routes/items/new.js, app/services/printer-service.js
https://jira.crossroads.org.hk/browse/GCW-3276
This PR adds new endpoint for updating and creating favourite printer for user in stock.
=> GCW-3276- Multiple favorite printers

app/styles/templates/_app_menu_list.scss, app/templates/app_menu_list.hbs
This PR is for new menu layout hover fix on menu item.
=> FIX => New Menu layout hover fix

app/controllers/orders/contact_summary.js, app/controllers/orders/detail.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/models/organisations_user.js, app/styles/_mixins.scss, app/styles/templates/orders/_detail.scss, app/styles/templates/stocktakes/_index.scss, app/templates/orders/contact_summary.hbs
jira.crossroads.org.hk/browse/GCW-3275
The user will be prompted to approve or deny the user before starting to process an order
=> GCW-3275 Processing requires approved user

app/styles/_main.scss, app/styles/templates/_app_menu_list.scss, app/templates/app_menu_list.hbs
https://jira.crossroads.org.hk/browse/GCW-3300
FEATURE: Hide box/pallet menu entries based on goodcity_settings
=> GCW-3300-Added a hide check on box and pallet based on goodcity settings

.circleci/config.yml, cordova/config.xml
https://jira.crossroads.org.hk/browse/GCW-3067
Removes "UIWebView APIs" for iOS
=> GCW-3067-Removing "UIWebView APIs" for iOS

app/styles/templates/components/_message_box.scss, app/styles/templates/components/goodcity/_designate_form.scss
https://jira.crossroads.org.hk/browse/GCW-3316
fixes layout issue of that screen also added scroll on modal for handling button hide in small size screen like iOS 5.
=> GCW-3316 - Adding packages to an order. Layout messed up

app/components/goodcity/offers-search-overlay.js, app/models/offer.js, app/templates/components/goodcity/offers-search-overlay.hbs
https://jira.crossroads.org.hk/browse/GCW-3179
FEATURE: Improve search feature for adding donor info to an item
=> GCW-3179-Improving search feature for adding donor info to an item

app/locales/zh-tw/translations.js, app/services/api-base-service.js, app/styles/templates/organisations/_search_organisations.scss, app/templates/search_organisation.hbs
https://jira.crossroads.org.hk/browse/GCW-3284
=> Pass language header and Fix the ios issue of search-bar shrink

app/components/goodcity/organisation-search-overlay.js, app/templates/organisations/detail.hbs, app/templates/organisations/nav_bar.hbs, app/templates/organisations/orders.hbs, app/templates/organisations/users.hbs
- Fix Navigation.
- Revert the footer added
=> Fix Navigation

app/templates/users/details.hbs
Fix Add Charity User Option Display
=> Fix Add Charity User Option Display 

app/components/goodcity/organisation-search-overlay.js, app/controllers/users/charity_position.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/styles/_search.scss, app/styles/templates/_user_details.scss, app/styles/templates/organisations/_new.scss, app/styles/templates/organisations/_search_organisations.scss, app/styles/templates/users/_charity_position.scss, app/styles/templates/users/_new.scss, app/templates/components/goodcity/organisation-search-overlay.hbs, app/templates/manage_users.hbs, app/templates/order/search_users.hbs, app/templates/users/add_user.hbs, app/templates/users/charity_position.hbs, app/templates/users/contact_details.hbs
User Management Screens CSS fixes
=> User Management Screens CSS fixes

app/styles/templates/components/_popup_overlay.scss
https://jira.crossroads.org.hk/browse/GCW-3317
BUG:  Keyboard blocks input field on confirmation page for Android
=> GCW-3317- Keyboard blocks input field on confirmation page for Android

app/locales/zh-tw/translations.js, app/styles/templates/components/_message_box.scss, app/styles/templates/users/_charity_position.scss, app/templates/users/charity_position.hbs
https://jira.crossroads.org.hk/browse/GCW-3281
Fix QA reported issues
=> :lipstick: Update UI - Fix QA issues and add translations

app/components/goodcity/offers-search-overlay.js, app/templates/components/goodcity/offers-search-overlay.hbs
https://jira.crossroads.org.hk/browse/GCW-3179
QA fixes for offer sorting
=> GCW-3179-Changes in offer sorting

app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/styles/templates/_user_details.scss, app/styles/templates/users/_new.scss, app/templates/users/add_user.hbs, app/templates/users/contact_details.hbs
https://jira.crossroads.org.hk/browse/GCW-3280
BUG: QA reported issue in add new user form fixed
=> QA fixes for add new user form added

app/components/contained-package.js, app/components/goodcity/add-item-overlay.js, app/controllers/items/detail.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/models/packages_location.js, app/routes/items/detail.js, app/templates/components/contained-package.hbs, app/templates/components/goodcity/add-item-overlay.hbs, app/templates/items/detail/tabs/storage_content.hbs, package.json
🚑 Hotfix 🚑 
- Refactored some dangerous code I found
- You cannot change the type of a box which has content, you must empty the box first
- Changing the type of a box will only show you the types of boxes
=> HotFix: Prevent boxes with wrong types

app/components/contained-package.js, app/components/goodcity/add-item-overlay.js, app/controllers/items/detail.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/models/packages_location.js, app/routes/items/detail.js, app/styles/templates/components/_message_box.scss, app/styles/templates/components/goodcity/_designate_form.scss, app/templates/components/contained-package.hbs, app/templates/components/goodcity/add-item-overlay.hbs, app/templates/items/detail/tabs/storage_content.hbs, package.json
🚑 Hotfix 🚑 
- Refactored some dangerous code I found
- You cannot change the type of a box which has content, you must empty the box first
- Changing the type of a box will only show you the types of boxes
=> [Release] [Hotfix] Prevent boxes from having wrong types

app/styles/templates/orders/_items.scss
https://jira.crossroads.org.hk/browse/GCW-3340
Fix the UI issue where Part of the first item on the 'Items' page is covered by the search bar
=> GCW-3340 Fix the Item list display UI

app/templates/organisations/users.hbs
https://jira.crossroads.org.hk/browse/GCW-3327
We will remove this link for now. And possibly add back this link later again to link to new user management screen
=> Remove Add User Link

app/constants/action-icons.js, app/helpers/item-action-icon.js
https://jira.crossroads.org.hk/browse/GCW-3347
fixed item action icons on history page
=> GCW-3347 fixed item action icons on history page

app/components/contained-package.js, app/components/goodcity/add-item-overlay.js, app/controllers/items/detail.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/mixins/item_actions.js, app/routes/items/detail.js, app/services/package-service.js, app/templates/components/contained-package.hbs, app/templates/components/goodcity/add-item-overlay.hbs, app/templates/components/goodcity/item-search-overlay.hbs, app/templates/components/package-summary-block.hbs, app/templates/items/detail/tabs/location.hbs, app/templates/items/detail/tabs/storage_content.hbs
https://jira.crossroads.org.hk/browse/GCW-3348
- Adds infinite scroll for items in box or pallet
- Improve on existing actions by adding callbacks to handle addition of items to box-pallets / removal of items from box-pallets in the infinite-scroll section
=> GCW-3348 Box Pallet Infinite Scroll

app/templates/components/package-summary-block.hbs
:bug: Fix location display if item is designated
=> Fix location display if item is designated

app/styles/templates/items/detail/_publishing_tab.scss, app/templates/components/goodcity/dispatch-form.hbs
https://jira.crossroads.org.hk/browse/GCW-3354
=> GCW-3354 fixed dispatch quantity input

app/components/print-label.js, app/controllers/items/new.js, app/services/printer-service.js
https://jira.crossroads.org.hk/browse/GCW-3301
This PR sends `tag` params for printing the favourite of the user.
=> GCW-3301- Selecting default printer while doing `print_label` command.

app/mixins/dispatch_actions.js
https://jira.crossroads.org.hk/browse/GCW-3313
fixed issue with dispatched quantity calculation in dispatch form
=> GCW-3313 fixed issue with dispatched quantity calculation in dispatch form

app/controllers/items/detail.js, app/templates/items/detail/tabs/_item_detail.hbs
https://jira.crossroads.org.hk/browse/GCW-3361
This PR fixes double request firing for `restriction` and `constraints` change.
=> GCW-3361 - Changing contraints on Item details generates two records on Item history tab.

app/styles/templates/components/_add_request.scss, app/templates/components/appointment-add-request.hbs
https://jira.crossroads.org.hk/browse/GCW-3333?focusedCommentId=41511&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-41511
BUG:  QA fixes for selecting good type
=> QA comment fix for selecting goods type while creating order

app/components/item-description-textarea.js, app/controllers/items/detail.js, app/controllers/items/new.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/models/item.js, app/styles/_main.scss, app/styles/templates/items/_detail.scss, app/styles/templates/items/_new.scss, app/templates/items/detail/tabs/_item_detail.hbs, app/templates/items/new.hbs
https://jira.crossroads.org.hk/browse/GCW-3381
The description field will now have two states (on English and one Chinese) in create, edit and view modes.
=> Gcw 3381 support pkg desc translation ii

.circleci/config.yml, app/components/online-button.js
https://jira.crossroads.org.hk/browse/GCW-3318
This PR fixes Reconnecting issue of mobile apps.
=> GCW-3318-Some phones display "Reconnecting..." when they are connected

app/templates/items/detail/tabs/_item_detail.hbs
=> Fix template attribute

app/models/user_profile.js, app/services/user-service.js
https://jira.crossroads.org.hk/browse/GCW-3283
fixed issue with role-update
=> GCW-3283 fixed issue with role-update

app/controllers/items/detail.js, app/helpers/delayed-action.js, app/styles/templates/items/_detail.scss, app/templates/items/detail/tabs/_item_detail.hbs
https://jira.crossroads.org.hk/browse/GCW-3380
Fixes issues reported during functional testing and QA testing
=> Fixes onfocusout action for saving item

app/components/goodcity/orders-package-block.js, app/services/designation-service.js, app/templates/components/goodcity/orders-package-block.hbs
Fixes:
- Redesignate defaults to the same order, user can later change it
- Issue in computing max quantity
=> GCW-2626 Redesignation fixes

app/components/mentionable-message-textbox.js, app/controllers/items/staff_conversation.js, app/controllers/orders/conversation.js, app/controllers/orders/staff_conversation.js, app/templates/orders/_message_template.hbs
https://jira.crossroads.org.hk/browse/GCW-3388
Allow valid users of stock app to be mentioned on chats
=> Allow valid users of stock app to be mentioned on chats

app/controllers/no-permission.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/router.js, app/routes/application.js, app/routes/no-permission.js, app/styles/app.scss, app/styles/templates/_no-permission.scss, app/templates/no-permission.hbs
https://jira.crossroads.org.hk/browse/GCW-3386
This PR adds no-permission routes for user trying to access endpoints with no permissions.
=> GCW-3386- Redirect User to Login page when stock-app access is removed for the logged-in User.

app/components/goodcity/offers-search-overlay.js
https://jira.crossroads.org.hk/browse/GCW-3073
Adding donor directly to package after scanning from barcode if donor exist
=> GCW-3073-Adding donor directly to package after scanning from barcode if donor exist

app/controllers/order/international_order.js, app/controllers/orders/staff_conversation.js
https://jira.crossroads.org.hk/browse/GCW-3236
BUG: Back button issue fix while creating international orders
=> GCW-3236 QA fix for back button issue while creating international orders 

app/templates/orders/_review_order_options.hbs
https://jira.crossroads.org.hk/browse/GCW-3398
This PR adds options in drop-down menu to cancel-order.
=> GCW-3398-Can't cancel orders where user has been declined

app/components/request-inline-input.js
https://jira.crossroads.org.hk/browse/GCW-3337
BUG:  It’s possible to add non-numerical characters to the ‘Quantity’ field on the ‘Requests’ tab of an order fix 
https://github.com/crossroads/stock.goodcity/pull/935/files#diff-bfab44f176137ef4816947d4af81ff0200e0edc09a1c987f5f6ca455d759e53cR25
=> GCW-3337-It’s possible to add non-numerical characters to the ‘Quantity’ field on the ‘Requests’ tab of an order fix

app/components/additional-fields-input.js, app/components/beneficiary-inline-input.js, app/components/order-inline-textarea-input.js
https://jira.crossroads.org.hk/browse/GCW-3360
Added `disableCallbacks` in  `willDestroyElement` hook for all inline edit components.
=> GCW-3360- willDestroy hook added for inline-components

app/models/designation.js, app/templates/orders/_order_status_bar.hbs, app/templates/orders/_review_order_options.hbs
https://jira.crossroads.org.hk/browse/GCW-3306
FEATURE: Orders work regardless of detail_type
=> GCW-3306 Orders work regardless of detail_type

app/controllers/items/detail.js, app/templates/items/detail/tabs/_sub_tabs.hbs
https://jira.crossroads.org.hk/browse/GCW-3385
FEATURE: Add total contents count to box and pallet
=> GCW-3385 Add total contents count to box and pallet

app/components/focus-textfield.js, app/components/goodcity/item-search-overlay.js, app/controllers/stocktakes/detail.js, app/services/barcode-service.js, app/services/cordova.js, app/styles/templates/stocktakes/_detail.scss, app/templates/_global_components.hbs, app/templates/components/goodcity/item-search-overlay.hbs, app/templates/stocktakes/detail.hbs, app/utils/async.js, app/utils/ember.js
Also:
- numeric keyboard
- bug fixes
=> GCW-3410 ADD: Stocktake flashlight

app/components/goodcity/code-search-overlay.js, app/mixins/preload_data.js, app/models/user.js, app/routes/index.js, app/routes/items/detail.js, app/routes/items/new.js, app/routes/orders/detail.js, app/routes/orders/order_types.js, app/templates/index.hbs, config/environment.js, tests/acceptance/item-details-tabs-test.js, tests/acceptance/item-inline-edit-test.js, tests/acceptance/order-details-appointment-info-test.js
https://jira.crossroads.org.hk/browse/GCW-3404
- Performance optimisations
- Remove unused preload requests
=> GCW-3404 Performance improvement

app/components/message-box.js
https://jira.crossroads.org.hk/browse/GCW-2867
This PR close the model on detecting browser back event.
=> GCW-2867- Popups don't disappear when the browser's back (or forward) button is used.

app/controllers/items/detail.js, app/routes/items/detail.js, app/services/package-service.js, app/templates/items/detail/tabs/_sub_tabs.hbs
jira.crossroads.org.hk/browse/GCW-3395?
FEATURE: QA fixes for total quantity counts in box and pallets
=> GCW-3395 QA fixes for total quantity counts in box and pallets

app/components/calendar-input.js, app/components/date-picker.js, app/templates/orders/_international_orders_summary.hbs
https://jira.crossroads.org.hk/browse/GCW-3422
BUG: Past shipments show wrong date because of minimum year restriction upto 2 years
=> GCW-3422-Remove minimum year restriction for shipments from calendar input component

app/routes/items/new.js
Note: **_ALWAYS_** await/return promises
=> HOTFIX: undefined restriction due to race condition

app/components/goodcity/item-search-overlay.js, app/controllers/items/detail.js, app/templates/_global_components.hbs, app/templates/items/detail/tabs/storage_content.hbs
https://jira.crossroads.org.hk/browse/GCW-3387
fetch packages associated with package-type-code
=> GCW-3387 fetch packages associated with package-type-code

app/components/date-picker.js
https://jira.crossroads.org.hk/browse/GCW-3422?focusedCommentId=42379&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-42379
BUG: Fix for setting shipment date instead of current day date in calendar panel
=> GCW-3422-Fix for setting shipment date instead of current day date in calendar panel

.circleci/config.yml, app/services/cordova.js
https://jira.crossroads.org.hk/browse/GCW-3423
This PR fixes the redirection issue on tapping the notification.
=> GCW-3423-Redirect to appropriate tabs on clicking the notification.

app/components/mentionable-message-textbox.js, app/templates/orders/_message_template.hbs
https://jira.crossroads.org.hk/browse/GCW-3388
Allow valid users to be mentioned in chats
=> GCW-3388 Allow valid users of stock app to be mentioned

app/controllers/users/contact_details.js
https://jira.crossroads.org.hk/browse/GCW-3401
This PR handles errors thrown from API for duplicate Email and reverts to old value in the input box.
=> FIX=> reverting old email value in case of error thrown from api

app/components/add-request.js, app/components/goodcity/code-search-overlay.js, app/controllers/items/detail.js, app/controllers/items/new.js, app/mixins/preload_data.js, app/routes/items/detail.js, app/routes/items/new.js, app/routes/stocktakes/detail.js, app/routes/stocktakes/index.js, app/services/package-type-service.js, app/templates/components/appointment-add-request.hbs, tests/acceptance/order-search-list-test.js
https://jira.crossroads.org.hk/browse/GCW-3439
- Resolves bug of valuation taking from previous package creation
- Resolve preload dependency problem
=> GCW-3434 Changing quantity affects UI of subsequent packages

app/components/add-request.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/templates/components/appointment-add-request.hbs
https://jira.crossroads.org.hk/browse/GCW-3430
Adds validation if the quantity is 0
=> GCW-3430 Add validation for goods quantity 

app/routes/index.js
=> Fix location loading

app/controllers/items/detail.js, app/controllers/items/new.js, app/routes/items/detail.js, app/routes/items/new.js, app/templates/items/detail/tabs/_item_detail.hbs, app/templates/items/new.hbs
https://jira.crossroads.org.hk/browse/GCW-3426
FEATURE: Remove set of fields from box and pallet
=> GCW-3426-Remove set of fields from box and pallet

app/templates/items/detail/tabs/_item_detail.hbs, app/templates/items/new.hbs
https://jira.crossroads.org.hk/browse/GCW-3426
BUG: Removed expiry date field for box and pallet
=> GCW-3426 Removing expiry date field from box and pallet

app/components/mentionable-message-textbox.js, app/controllers/items/detail.js, app/controllers/orders/conversation.js, app/models/user_profile.js, app/styles/templates/orders/_detail.scss, app/templates/manage_users.hbs, app/templates/orders/_message_template.hbs, app/templates/orders/_order_tabs.hbs, app/templates/users/contact_details.hbs
https://jira.crossroads.org.hk/browse/GCW-3388
Add restrictions for user mentioning
=> GCW-3388 Add restrictions for mentioning users

app/locales/zh-tw/translations.js
https://jira.crossroads.org.hk/browse/GCW-3396
Adds Stocktake translation for zh-tw
=> GCW-3396 Adds Stocktake translation for zh-tw

app/constants/regex.js, app/controllers/users/contact_details.js
https://jira.crossroads.org.hk/browse/GCW-3401
Fix added for breaking email changes in user management screen
=> GCW-3401-Fix added for breaking email changes in user management screen

app/routes/item_filters.js
https://jira.crossroads.org.hk/browse/GCW-3384
Fix location not being displayed sometimes on item index page
=> GCW-3384 Fix location not being displayed sometimes on item index page

app/constants/action-icons.js, app/controllers/items/history.js, app/models/orders_package.js, app/styles/templates/items/_history.scss, app/templates/items/_item_action_block.hbs, app/templates/items/sticky_footer.hbs
https://jira.crossroads.org.hk/browse/GCW-3403
This PR adds Designated action in history.
=> GCW-3403- Adding Missing actions on history tab 

app/controllers/items/detail.js, app/models/item.js, app/routes/items/detail.js, app/templates/components/offer-tag.hbs, app/templates/items/detail/tabs/_item_detail.hbs
https://jira.crossroads.org.hk/browse/GCW-3467
BUG: Stock users were not able to view items through orders page
=> GCW-3467-Removed offer reloading for items from stock app

app/constants/action-icons.js, app/controllers/items/history.js, app/helpers/format-display-value.js, app/models/item_action.js, app/templates/items/_item_action_block.hbs
https://jira.crossroads.org.hk/browse/GCW-3403
This PR adds UI for rendering versioning of Orders-Packages actions and fix minor icons bugs.
=> GCW-3403- Adding versioning to orders packages actions

app/styles/templates/components/_package_summary_block.scss, app/templates/items/new.hbs
https://jira.crossroads.org.hk/browse/GCW-3329
BUG: Stock: It's possible to create items with the Inventory# with non-numerical characters fix.
=> GCW-3329 Non Numerical character in inventory number fix

app/controllers/order/search_users.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js
https://jira.crossroads.org.hk/browse/GCW-2850
fixed creating orders for users without org
=> GCW-2850 fixed creating orders for users without org

app/mixins/preload_data.js, app/routes/items/index.js, app/routes/orders/index.js, app/services/user-service.js
https://jira.crossroads.org.hk/browse/GCW-3491
The header sent for `current_user_profile` request was always 'en', and hence the preferred language wasnt being updated
=> GCW-3491 Fix wrong language headers sent

app/styles/templates/items/_detail.scss, app/templates/items/detail/tabs/_item_detail.hbs
https://jira.crossroads.org.hk/browse/GCW-3505
Fix Description's automated suggestion selection for an item
=> GCW-3505 It's difficult to select the Description's automated suggestion for an item.

app/controllers/items/detail.js, app/templates/items/detail/tabs/_item_detail.hbs
https://jira.crossroads.org.hk/browse/GCW-3509
BUG: Remove hiding the default value
=> GCW-3509-Make default value selectable without focus in

app/controllers/orders/client_summary.js
https://jira.crossroads.org.hk/browse/GCW-3504
Fix something went wrong on changing people benefited field
=> [GCW-3504] Fix something went wrong on changing people benifitted field

app/controllers/users/details.js, app/models/user_profile.js, app/templates/users/details.hbs
https://jira.crossroads.org.hk/browse/GCW-3529
Display the add / edit charity option based on permission
=> GCW-3529 Fix permission related bug for charity position

app/styles/templates/orders/_detail.scss
https://jira.crossroads.org.hk/browse/GCW-3539
This PR adds `height:100vh` to the overlay area of the calendar.
=> GCW-3539-The calendar shows up but unable to choose the date, possibly a resolution problem

app/routes/orders/order_types.js, config/environment.js
=> Add districts in preload data

app/styles/templates/components/_package_summary_block.scss
https://jira.crossroads.org.hk/browse/GCW-3514
FEATURE: Prevents overflow of texts in the item description
=> GCW-3514-Prevent overflow of item description

app/controllers/orders/detail.js, app/controllers/orders/order_types.js
https://jira.crossroads.org.hk/browse/GCW-3269
Format the scheduledAt date under logistic details in stock app
=> GCW-3269 - Change format of scheduled at date for offer

app/controllers/items/detail.js
https://jira.crossroads.org.hk/browse/GCW-3061
Live update issues related to Box pallet item addition/removal
=> GCW-3061 - Resolve live update issues related to Box pallet item addition/removal

app/components/goodcity/code-search-overlay.js, app/components/goodcity/item-search-overlay.js, app/components/goodcity/offers-search-overlay.js, app/components/goodcity/organisation-search-overlay.js
https://jira.crossroads.org.hk/browse/GCW-3424
Resolve issue for search overlay . Close search overlay when browser back button is clicked
=> GCW-3424 - Close search overlay when browser or mobile back button is clicked

app/controllers/users/details.js, app/controllers/users/merge_user.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/models/user_profile.js, app/router.js, app/routes/application.js, app/routes/users/details.js, app/routes/users/merge_user.js, app/services/user-service.js, app/styles/templates/_user_details.scss, app/templates/manage_users.hbs, app/templates/users/_disable_user_popup.hbs, app/templates/users/_user_row.hbs, app/templates/users/details.hbs, app/templates/users/merge_user.hbs
https://jira.crossroads.org.hk/browse/GCW-3629
Merge User Feature
Mockup: https://xd.adobe.com/view/e37fda19-82ce-4786-8b1d-d580409bb704-b62c/screen/cc250724-172f-4a64-bd88-7aa458f46c59/?x_product=xd-jiraserver%2F1.0
=> GCW-3629 Merge Users

app/controllers/application.js, app/controllers/authenticate.js
https://jira.crossroads.org.hk/browse/GCW-3061
Fix live updates on mobile app when User logs in Stock app
=> GCW-3061 - Fix live update issue on mobile app when User logs in first time

app/controllers/items/detail.js, app/routes/items/detail.js, app/routes/items/index.js
https://jira.crossroads.org.hk/browse/GCW-2836
fixed accessing item with state-missing and no-inventory-number
=> GCW-2836 fixed accessing item with state-missing and no-inventory-number

app/components/donation-inline-input.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/templates/components/donation-field.hbs, tests/acceptance/item-inline-edit-test.js
https://jira.crossroads.org.hk/browse/GCW-2866
Removed CAS number validation
=> GCW-2866 removed CAS number validations

app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/models/stocktake.js, app/styles/templates/stocktakes/_detail.scss, app/templates/stocktakes/detail.hbs
While Sidekiq is processing a Stocktake, its status will be `awaiting_process` followed by `processing`, during that time we show an overlay on the page explaining to the user that the Stocktake is being processed.
=> ADD: stocktake processing overlay

app/routes/items/detail.js, app/services/messages.js, package.json
Fixed retrieving of item messages.
=> [Release] Hotfix 0.23.1

app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/styles/templates/orders/_detail.scss, app/templates/orders/_cancel_message_popup.hbs
NOTE: https://jira.crossroads.org.hk/browse/GCW-3692
Improves warning text for cancel order
=> GCW-3692- Adding warning to cancel order popup

app/services/barcode-service.js, app/utils/barcode-ui.js
When the fullscreen bardcode scanner UI appears, we want to have a "Light" button which toggles the phone's flashlight.
=> GCW-3691 ADD: light button to barcode scanner UI

app/controllers/stocktakes/detail.js, app/styles/templates/stocktakes/_detail.scss, app/templates/stocktakes/detail.hbs
ADDED: A search field on the stocktake details page that acts as a filter.
=> ADDED: Stocktake search field

app/controllers/stocktakes/detail.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/models/stocktake_revision.js, app/services/session.js, app/styles/_checkbox_styles.scss, app/styles/templates/items/_new.scss, app/styles/templates/stocktakes/_detail.scss, app/templates/components/item-filter-checkbox.hbs, app/templates/stocktakes/detail.hbs
Adds a "Only mine" checkbox that filters only the revisions I've counted.
=> STOCKTAKE: allow filtering my own items

app/components/external-link.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/router.js, app/styles/templates/_login.scss, app/templates/login.hbs, app/templates/pics.hbs
https://jira.crossroads.org.hk/browse/GCW-3728
PICS page
=> GCW-3728 PICS page

app/components/qr-code.js, app/styles/templates/_access_pass.scss, app/templates/display_access_pass.hbs, bower.json, ember-cli-build.js
https://jira.crossroads.org.hk/browse/GCW-3718
QR code for access-pass
=> GCW-3718 QR code for access-pass

app/controllers/stocktakes/detail.js, app/locales/en/translations.js, app/locales/zh-tw/translations.js, app/styles/templates/stocktakes/_detail.scss, app/templates/stocktakes/detail.hbs
We can now control the sorting order of Stocktake revisions with a dropdown
=> ADD: Stocktake Sorting
