- Rakefile
- circle.yml
- cordova/build.json
- cordova/config.xml
- package.json
Hi Team,
This PR upgrades the following.
- Cordova-ios to `4.5.4`
- XCode to `9.2`
- Cordova to lastest version
Downgrades:
- Ember-cli to 2.11(as it was failing with node engine needed >=4.5 || 6 error, which we already have but 2.11 seemed to be working so downgraded to 2.11)
Removes from Circle.yml
- Cordova(as we're installing cardova in rakefile so not needed)
- ember-cli(installing through package.json so not needed)
- Watchmen(only needed to run test cases, in case watchmen is not installed them ember test falls back to node which is fine)
Changes needed to make XCode `9.2` get working on CI
- Add `developmentTeam` id to build.json or directly to cordova build command (developmentTeam id can be found here => https://developer.apple.com/account/#/membership/6B8FS8W94M )
- From XCode …
> GCW 1998 xcode upgrade

- app/models/contact.js
- app/templates/orders/order_transport.hbs
- tests/unit/model/contact-test.js
Hi Team,
This PR adds Address detail for GGV transport on GGV page of Orders detail page.
Jira ticket:- https://jira.crossroads.org.hk/browse/GCW-2086
please review it and let me know if any further changes are required.
Thanks
> GCW 2086 add address to ggv order detail page

- circle.yml
Hi Team,
This PR uses CodeClimate's **test-reporter** as it has support for parallel builds, multiple languages, and will receive ongoing support from CodeClimate in the future. 
The reason for change is we were using  older, deprecated test reporter which wasn't showing code-coverage correctly so we're hoping to fix the issue with this.
Test-reporter:- https://github.com/codeclimate/test-reporter
Configuration:- https://docs.codeclimate.com/docs/configuring-test-coverage
Please take a look and let me know if any further changes are required.
Thanks
> Code climate test coverage changes

- app/locales/en/translations.coffee
- app/locales/zh-tw/translations.coffee
Hi team, 
A translation is missing in prod.
It only affects draft orders. Was not originally added as drafts are not in the scope of the orders page's design, but actually are available the context of the items/orders page (designating).
> Missing draft translation

- app/controllers/orders/items.js
Crash happening due to `data.removeObject(item);` within a forEach loop.
Items in the following iterations would be undefined, which caused `item.get("quantity");` to break
Tiny fix but I added a bit of refactoring while I'm at it :)
> FIX: Crash due to item removed from list during forEach

- app/controllers/orders/detail.js
- app/locales/en/translations.coffee
Hi Team,
This PR removes constraint `at least 1 designated item required to cancel order and keeps constraint of no dispatched items.`
https://jira.crossroads.org.hk/browse/GCW-2294
I will ask Nokia or someone to change chinese translation once this PR is merged.
Please review.
Thanks.
> GCW-2294 relax designation constraint to cancel order

- app/routes/application.js
- app/styles/templates/components/_item_options_list.scss
- app/styles/templates/items/_detail.scss
- app/styles/templates/orders/_detail.scss
- app/templates/items/detail.hbs
- app/templates/orders/item_block.hbs
- Fixed the issue where a popup would appear on startup that we couldn't close.
- Fixed various zones where clicking was hard, by increasing the clickable-zone
Regarding the syntax error, it's quite interesting : 
When using commas in a lambda (without brackets), it only evaluates the first expression
e.g 
```javascript
let fn = () => console.log('a'), console.log('b')
```
is the equivalent of 
```javascript
let fn = () => { console.log('a') };
console.log('b')
```
and **NOT** 
```javascript
let fn = () => { console.log('a'), console.log('b') }
```
So in this scenario, the `alert` method was actually receiving the value of `this.transitionTo('login')`, which is likely undefined, which means there was no callback. 
At least I hope this is the fix, given that it's hard to reproduce. But …
> GCW-2326 + GCW-2293

- app/templates/orders/contact.hbs
- app/templates/orders/order_block.hbs
- app/templates/orders/summary.hbs
- tests/acceptance/order-organisation-and-contact-test.js
Hi Team,
On Stock app order details we were showing submitted_by instead of created_by. 
In case of appoint creation on behalf of user it looks wrong. We should show contact and other details of user for whom we have created order.
Issue mentioned on ticket: https://jira.crossroads.org.hk/browse/GCW-2246
Please review.
Thanks.
> replace submitted_by with created_by

- app/routes/orders/detail.js
Hi team,
Here's a fix for the issue where we set an order to 'processing' and it switches immediately back to the previous state (if done quickly enough).
The cause of this appears to be coming from the `findRecord` ember store method with option : `{reload:false}`
--> in that scenario, Ember will return the local record immediately **however**, it will still make a request in the background regardless (which resolves later on its own, ignoring any promise `await`)
This might seem harmless, but since each request also comes with dependencies, it can actually alter data randomly on the page, with no way for us to track it #emberHell 
A reference: https://stackoverflow.com/questions/39899302/emberjs-findrecord-then-not-waiting-for-resolve
> Fix: race condition issue causes order state jitters

- app/controllers/orders/order_types.js
- app/locales/en/translations.coffee
- app/locales/zh-tw/translations.coffee
- app/models/designation.js
- app/models/gogovan_transport.js
- app/models/order_transport.js
- app/styles/templates/orders/_detail.scss
- app/templates/orders/order_types.hbs
- tests/acceptance/order-details-appointment-info-test.js
Adds extra lines of data to the logistic tabs. Those are not yet editable.
From the design :
> GCW-2366 logistics tab : Add rows

- package.json
- yarn.lock
This PR removes jshint from stock, 
We dont need jshint any longer because we have started using 
`lint-staged` it automatically finds the jshint issues and fixes them before commit
Thanks
> remove jshint as we have other linters

- app/routes/items/search_order.js
Hi Team,
This is fix for wrong popup for designated item on item search page. The issue was due to previous queryparams not getting cleaned up. Issue is fixed.
Thanks.
> FIX => Wrong redesignate popup on item search page

- app/components/order-filters.js
- app/controllers/index.js
- app/controllers/orders/index.js
- app/helpers/state-filter-icon.js
- app/routes/orders/index.js
- app/services/filter-service.js
Hi, 
A lot of this code is some cleanup and refactoring (because I have a problem and can't stop myself)
But the real bug comes from this line :
`filter.shift();`
This `shift` function **_mutates_** the array, which is never a good idea. We **always** want to write immutable code.  Here it (accidentally) modifies the data of another module, the best way to avoid those potential issues, is to never modify anything (leading to functional programming)
One other potential issue here, was that the code assumed that a certain element was placed first in an array. (assumptions in themselves are dangerous, we want to build deterministic systems)
So here, to remove a certain item from an array, I replaced a `.slice(1)`  with a `filter` call, which leaves no room for ambiguity
> FIX => Filter array was being modified

- app/controllers/search_organisation.js
- app/templates/search_organisation.hbs
Hi Team,
This PR is for JIRA ticket GCW-2534- Organisation not searchable with half organisation name. Possible reason for not displaying the expected results is because we are restricting only 25 records from api. I have added pagination along with scrolling in the search organisation page. This will fix this issue.
Please review the PR and let me know if any changes is required.
> GCW-2534- Organisation not searchable

- app/services/subscription.js
The new push updates changes on api (https://github.com/crossroads/api.goodcity/pull/743) no longer send orders as "designations" (which is a good thing, we want to move away from this terminology).
This PR adds an alias to the subscription service (`order` -> `designation`) in order to support the new updates.
> Live updates: Support order model (locally named designation)

- app/controllers/items/new.js
- app/controllers/search_code.js
- app/controllers/select_location.js
- app/instance-initializers/ajax.js
- app/routes/items/new.js
- app/services/processing-checklist.js
- app/templates/items/new.hbs
- yarn.lock
The previous issue that was found for images was related to having a bad page state. 
One problem found related to that, is that using the native back button bypasses function calls which are meant to clear/restore state, which leads to even more problems.
Here the solution is to use `replaceWith` instead of `transitionTo`, which solves 2 things: 
- a better user experience since we don't land back into pages which are meant to be "transitional" 
- it prevents from returning to an unknown/incomplete state, which eventually led to images breaking
Generally we want to use `replaceWith` when it comes to search pages (organisations, etc) as they are designed more as popups, so we don't want to keep a history of it.
FYI: If you want to use a replace behaviour with a `link-to` hbs helper, that …
> Image fixes (back link related) + Default headers for AjaxPromise

- app/components/designate-form.js
- app/styles/templates/components/_item_options_list.scss
- app/templates/components/item-options-list.hbs
Hi Team,
This PR is fix for Tim's last comment on GCW-2577- Designating cancelled orders page. While designating cancelled packages in order which is not designated to other orders gives error. And also minor css fix for `undispatch` icon on Item search page. 
Thanks.
> FIX => For error during designating cancelled package (which is not designated to any order)

- app/serializers/designation.js
Hi Team, this PR includes fixes for organisation missing on few orders. 
The issue which was there was due to the reason of json params we were sending to the API. 
Whenever we update anything in the order from the logistics tab, the updateRecord method was called which caused the use of serializer method. In the params, `organisation_id` was sent null and due to that organisation was removed from the order, and similarly for stockit_organisation, it was updating the GC organisation id in the order. 
I have modified the json just how the api likes it. We'll be sending `stockit_organisation_id` and `organisation_id` param to the API, so that it wont cause the above mentioned issue. 
Please review.
Thanks
> GCW-2576 update payload according to api

- app/locales/en/translations.js
- app/locales/zh-tw/translations.js
- app/routes/application.js
- app/routes/authorize.js
Currrently, if user is logged out and tries to visit any page, we show "You must login!" modal, which looks rude, so this PR removes that modal, and automatically redirects them to the login page.
Keeping in mind which the user was trying to visit, post login user is redirected to that page.
> redirect users to login page instead of showing modal

- app/locales/en/translations.js
- app/locales/zh-tw/translations.js
Hi team, 
This PR's adds back the tranlations which went missing when we changed the translations file from `.coffee` to `.js`.
Thanks
> GCW-2618 fix missing translations

- app/controllers/items/detail.js
- app/templates/items/detail/tabs/info.hbs
https://jira.crossroads.org.hk/browse/GCW-2780
- **Missed scenario fixture**: If there is a package_type which has allow_pieces set to false. The pieces in-line edit was available on item details screen. It has now been taken care of.
https://jira.crossroads.org.hk/browse/GCW-2780?focusedCommentId=36166&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-36166
- Item detail page.
> GCW-2780 hide pieces inline edit if allow_pieces is false

- app/components/goodcity/orders-package-block.js
- app/initializers/session.js
- app/mixins/navigation_aware.js
- app/services/designation-service.js
- app/services/location-service.js
- app/services/subscription.js
- app/templates/components/goodcity/locations-search-overlay.hbs
- app/templates/components/goodcity/orders-search-overlay.hbs
https://jira.crossroads.org.hk/browse/GCW-2779
Fixing a couple of issues reported by Tim :
- Due to background reloads, the string "Multiple location" would sometimes appear for a second
- Overlays would not close when navigating away from a page
- Changed the overlay close icons, to differentiate them from "back" navigation actions
Created a `NavigationAwareness` mixin, which can be used to respond to navigation
> Close overlays on navigation

- app/controllers/items/detail.js
- app/templates/items/detail/tabs/info.hbs
NOTE: https://jira.crossroads.org.hk/browse/GCW-2780
BUG: If weight input field has characters more than 4, it used to cut off. Overlapped by unwanted space
NOTE: This PR fixes that issue.
Item details view screen
> GCW-2780 fix overlapping issue of weight input field on mobile screens

- .circleci/config.yml
- cordova/config.xml
- fastlane/Fastfile
https://jira.crossroads.org.hk/browse/GCW-2854
It upgrades the android version to point API level 28. 
Starting November 1, 2019, updates to apps and games on Google Play will be required to target Android 9 (API level 28) or higher. After this date, the Play Console will prevent you from submitting new APKs with a targetSdkVersion less than 28.
NOTE:  Circle ci 2 provides environment variable `CIRCLE_ARTIFACT` which we used previously and it used to point to the path where apk used to save on CI. 
`CIRCLE_ARTIFACT` path = /home/circleci/code/cordova/platforms/android/build/outputs/apk/*.apk
Path where APK gets created after android 7 = /home/circleci/code/cordova/platforms/android/app/build/outputs/apk/debug/*.apk
Thus I have replaced `CIRCLE_ARTIFACT` with new required path. …
> GCW-2854 upgrade android api to 28

- app/components/goodcity/orders-package-block.js
- app/helpers/back-action.js
- app/styles/templates/components/_side_drawer.scss
- app/templates/components/back-link.hbs
- app/templates/components/goodcity/orders-package-block.hbs
- app/templates/orders/_orders_back_link_path.hbs
Quick addition to https://jira.crossroads.org.hk/browse/GCW-2779
When clicking on an orders_package block on the Item details page, it redirects to the order details
Item details > publishing tab > orders_package block
Created a `back-link` component which uses the default browser back navigation. We've long known that hardcoding the back links it not acceptable, so hopefully this is a stepping stone
```
{{#back-link}}
<div> Click me to go back ! </div>
{{/back-link}}
```
> Clicking on an orders_packages navigates to order detail

- app/components/goodcity/orders-package-block.js
- app/styles/_colors.scss
- app/styles/templates/components/goodcity/_orders_package_block.scss
- app/templates/components/goodcity/orders-package-block.hbs
- app/templates/orders/active_items.hbs
GCW-2779
Use the `orders_package` blocks that got created for GCW-2779 on Order > Goods tab.
Given that they are the exact same thing but look slightly different I added a `packageView=true` flag which allows to toggle between the 2 display modes.
No differences apart from that.
Orders > Goods tab
> Use new orders_package component on the orders details page

- app/styles/_search.scss
- app/styles/templates/_index.scss
- app/styles/templates/items/_detail.scss
- app/styles/templates/orders/_items.scss
- app/templates/items/_item_back_link.hbs
- app/templates/items/search_order.hbs
https://jira.crossroads.org.hk/browse/GCW-2309
This PR solves following issues:
1. the back arrow on the item page is still too low on Desktop and slightly too low on the tablets.
(Left screenshot is desktop, right screenshot is tablet (iPad)).
2. On the Designate item to order page, the icon next to the back button is not aligned with the text on desktops or mobiles.
(left screenshot is desktop, right screenshot is mobile).
3. The text on the "Orders In Process" buttons are still cut off the bottom when using settings for large displays.
Screenshots:
Please review 
Thanks
> Gcw 2309 stockapp css issues

- app/controllers/items/detail.js
- app/controllers/items/select_code.js
https://jira.crossroads.org.hk/browse/GCW-2928
BUG:  
1) when changing the package type from one with extra fields that have content in them to the same package type (or a different one with the same extra fields), the contents in the 'Country of Origin' dropdown field is deleted.
2) older items with a package type that should have the extra fields (but don't) can have their package type changed to a different package type and back again to have the extra fields, but a different package type must be first selected. If the the same package type is first chosen and then a different package type, the confirmation pop-up appears but doesn't continue past the package type selection page.
Item detail screen.
> GCW-2928-edit subform

- config/environment.js
Turns off Rollbar for development environment
BUG: When reporting rollbar errors, we're not interested in development environment ones.
The docs for ember-rollbar-client (v0.9) indicate that development environment is ignore, however, we are currently using v0.2.2 which only ignores testing. We need to add this clause back in.
> Old rollbar client needs to be disabled on dev envs.

- app/controllers/search_organisation.js
Remove reference to old (and soon to disappear) `search_module`
This search had been refactored with the new infinite list, but the reference to the old search_module was still there. And it was trimming the chinese characters out of the search text.
I simply removed that reference which is not needed.
> String sanitization prevents chinese characters in the organisation search

- app/controllers/orders/detail.js
https://jira.crossroads.org.hk/browse/GCW-2932
This PR is part of bug related to displaying of orders_packages count on  order details page.
Earlier orders_pages was incrementing on each scroll pagination. This PR fixes that.
> FIX=> Showing correct orders_packages count on order details page.

- app/initializers/browser_compatibility.js
`Promise.finally` does not exist on Edge, causing a lot of issues which are often reported by Tim(s)
This little fix simply adds the `finally` method when not available
> Edge compatibility fix

- app/controllers/orders/detail.js
- app/templates/orders/_order_tabs.hbs
- app/templates/orders/_summary_tabs.hbs
https://jira.crossroads.org.hk/browse/GCW-3007
BUG: Sub-tabs(Contact and Purpose/client) under order summary  were not getting highlighted.
Fix: Added is-equal helper in template of orders.summary_tabs and also defined a computed property highlightSelectedTab in controller of orders/detail.js and used it in template of orders_tabs
Home>Recent Order> Select Any order>Summary
highlightSelectedTab
> GCW-3007 create computed property for highlighting

- app/components/scan-barcode-button.js
https://jira.crossroads.org.hk/browse/GCW-3049
BUG: On Scan barcode "length of undefined" error pop ups.
This PR sends sanitized searched input to "onScanComplete" callback.
> GCW-3049-Scanning barcode on offers search on overlay throws error.

- app/locales/en/translations.js
- app/locales/zh-tw/translations.js
- app/templates/items/index.hbs
https://jira.crossroads.org.hk/browse/GCW-3045
Add Item inventory button was not appearing in items tab of stock app
BUG: Previously the button was not appearing in the items tab if there is no result, But now the issue is resolved 
Issue present in https://jira.crossroads.org.hk/browse/GCW-2652 is also resolved
> GCW 3045: Add inventory button not appearing fix

- app/components/goodcity/offers-search-overlay.js
- app/locales/en/translations.js
- app/locales/zh-tw/translations.js
- app/routes/items/new.js
- app/styles/templates/components/_offer_tags.scss
- app/styles/templates/components/goodcity/_search_overlay.scss
- app/styles/templates/items/_detail.scss
- app/styles/templates/items/_new.scss
- app/templates/components/goodcity/offers-search-overlay.hbs
- app/templates/components/offer-tag.hbs
- app/templates/items/detail/tabs/_item_detail.hbs
https://jira.crossroads.org.hk/browse/GCW-2863
Fixed following:
- When creating an item/box/pallet, if the browser's back button is used or if the item/box/pallet is cancelled, any previously selected users will remain when creating a new item/box/pallet. (Creating the item/box/pallet will remove all users)
- On the iPad, when scanning an invalid barcode for the first time the app is opened, the 'null is not an object (evaluating 'this.get("searchText").length')' pop-up message appeared.
-On the Pixel after adding a user, if another field is selected then the size of the user will increase.
- Scanning barcodes doesn't work for me at all. The first time a barcode is scanned there is an error message (as mentioned by Tim Walton), and after that nothing happens when scanning.
- When using a …
> GCW-2893-Offer package link UI fixes

- app/controllers/items/new.js
GCW-2859
Removes the publish icon checkbox from the form while creating a box/pallet.
> GCW-2859 hide publish checkbox if box/pallet

- app/controllers/orders/detail.js
https://jira.crossroads.org.hk/browse/GCW-2931
BUG: On cancelling order with dispatch orders_packages throws error but it was not displayed. This PR catches that error and show on modal.
> FIX=> Catch and Show error on modal on cancelling dispatch order

- app/styles/templates/components/goodcity/_search_overlay.scss
- app/templates/components/goodcity/offers-search-overlay.hbs
https://jira.crossroads.org.hk/browse/GCW-3071
Displays the X in correct place both in mobile as well as web app
> GCW-3071 Button is working and displayed Stock: The 'x' button to clear the offer search field is displayed in the wrong place fix

- app/templates/items/detail.hbs
**https://jira.crossroads.org.hk/browse/GCW-3042**
BUG: Fixes dispatch icon on items details screen
`dispatchOrdersPackagePopUp` action was called onClick, but nothing was handled in the controller for that action. 
Removed it completely and it will now work as the designate icon.
i.e. Transition to publishing page, and let the user perform operations.
> GCW-3042 fix dispatch icon on item detail screen

- app/models/offer.js
This PR is for displaying correct received duration time on offers-search overlay.
Issue: It was showing "few seconds ago" duration for all offers on offers-search overlay.
Reason for issue:  `received_at` field was not coming in `offer` model response.
> FIX=> wrong offers received duration on offers search

- app/templates/orders/_order_status_bar.hbs
https://jira.crossroads.org.hk/browse/GCW-3078
BUG: on stock orders details page, submitted at date was picking up the wrong value. i.e. createdAt.
Fixed that issue
> GCW_3078 created_at date shown as the "Submitted date" fix

- app/models/offer.js
- package.json
Hi Team,
This PR fixes wrong `received_at` duration on Offer search overlay.
> FIX=> wrong offer received_at duration on offers search overlay

- app/components/goodcity/orders-package-block.js
- app/components/item-options-list.js
- app/components/quantity-chooser.js
- app/controllers/items/detail.js
- app/mixins/designation_actions.js
- app/mixins/dispatch_actions.js
- app/models/item.js
- app/models/orders_package.js
- app/models/set_item.js
- app/routes/items/index.js
- app/templates/components/goodcity/add-item-overlay.hbs
- app/templates/items/_item_description.hbs
- app/templates/items/detail/_tabs.hbs
- app/templates/items/detail/tabs/_item_detail.hbs
- app/templates/items/detail/tabs/location.hbs
- app/templates/items/detail/tabs/publishing.hbs
- tests/acceptance/split-quantity-of-items-test.js
- tests/controller/item-details-test.js
- tests/factories/item.js
- tests/unit/model/item-test.js
- tests/unit/model/orders-package-test.js
- tests/unit/model/set_item-test.js
This PR is dependant on https://github.com/crossroads/api.goodcity/pull/926
- Addition of the following fields to the `item` model (which is actually a `package`)
* `availableQuantity`
* `onHandQuantity`
* `dispatchedQuantity`
* `designatedQuantity`
- The `quantity` field is now an alias to `availableQuantity` (as a temporary safeguard)
- Computed quantities `totalDesignatedQty` and `totalDispatchedQty` substituted with the actual fields
- Changed all the reads of old quantities I found to the new properties
> Remove quantity field

- app/adapters/designation.js
- app/controllers/items/index.js
- app/models/item.js
- app/routes/orders/detail.js
- app/services/designation-service.js
https://jira.crossroads.org.hk/browse/GCW-3085
I've removed some repeated `GET` request of order show action. Also made some changes in models which ultimately remove `order` async `GET` request on `items` search page (which is the main source of error on rollbar).
There are multiple area where we need to inspect performance improvement.
- Order details page (going into orders)
- Items search page: on doing infinite scrolling on Items search page there isn't any `GET` request  for Orders.
> GCW-3085-Order show action performance improvement

- app/services/subscription.js
As titled. We merge the data without doing a fresh fetch.
Possible regressions: dependencies updated but not reflected inn the app
> Remove package fetch on live updates

- app/templates/orders/_items_list_tabs.hbs
https://jira.crossroads.org.hk/browse/GCW-2945
As per discussion on the ticket, the request tab should be only visible on GoodCityOrders.
Please review.
Thanks.
> show request tab on order only for goodcity orders

- app/controllers/orders/items.js
- app/routes/orders/items.js
- app/templates/orders/active_items.hbs
- app/templates/orders/items.hbs
https://jira.crossroads.org.hk/browse/GCW-3091
BUG: Removed observers for search input query params. Used "onScanComplete" callback for search Items page to avoid usage of observers.
NOTE: 1) Orders Active Items page 2) Search items page for orders.
> GCW-3091-back button issue on orders Item search

- app/styles/templates/components/_side_drawer.scss
https://jira.crossroads.org.hk/browse/GCW-2951
Arrow button now appear correctly in small screens
> GCW-2951-Fixed arrow issue in active_items page

- app/routes/orders/client_summary.js
- tests/acceptance/purpose-test.js
https://jira.crossroads.org.hk/browse/GCW-3112
BUG:  Due to shallow loading of orders in search, beneficiary association isn't getting load. This PR adds explicit beneficiary request in client summary page.
Orders -> Client Summary
> GCW-3112-Client name appears as 'undefined undefined' when a new order is created from Browse

- app/models/user_profile.js
- app/templates/app_menu_list.hbs
https://jira.crossroads.org.hk/browse/GCW-3121
The `Create New Order` would be shown to users who had `can_manage_settings` permissions. It needs to be shown to users who have `can_manage_orders` permissions
Create new orders
https://github.com/crossroads/api.goodcity/pull/976
> GCW-3121 Show create orders for users with order permissions

- app/templates/components/package-summary-block.hbs
- package.json
The eye icon on package blocks is now crossed when unpublished
> GCW-3129 package block publish status

- app/controllers/items/detail.js
- app/templates/items/detail/tabs/_item_detail.hbs
https://jira.crossroads.org.hk/browse/GCW-3130
Fixes the bug, where in item detail screen if any field is updated the expiry date field is set to null
> GCW-3130 Fix resetting of expiry date on update action

- app/controllers/items/detail.js
- app/locales/en/translations.js
- app/locales/zh-tw/translations.js
- app/services/package-service.js
- app/services/package-type-service.js
- app/templates/_global_components.hbs
- app/templates/components/goodcity/code-search-overlay.hbs
- app/templates/items/detail/tabs/location.hbs
Issues found while testing:
* Creating a set prompts to select a package type, but it only shows the Parent types, without the type itself
* Missing text to the overlay to indicate what they are picking
* Missing translation
> [FIX] Package type selection overlay

- app/components/editable-line.js
- app/controllers/items/detail.js
- app/models/item.js
- app/services/package-service.js
- app/templates/components/editable-line.hbs
- app/templates/items/detail/_set_header.hbs
Fix of the following issues reported by Tim:
- If a set is removed and then immediately created again, it doesn't reappear on the UI untill the page is reloaded.
- the item search UI is not shown immediately when creating a set. See the requirement under point 3 of 'Creating a new set'
- If the description of a set is edited but the user leaves the page without selecting the save button, the changes are still saved.
- When editing the description of a set, it is possible for the description to be saved when it is empty.
> GCW-3101 QA Fixes

- app/routes/orders/active_items.js
- app/templates/orders/index.hbs
- tests/acceptance/order-redispatch-test.js
- tests/acceptance/order-restart-processing-test.js
- tests/acceptance/order-resubmit-cancel-test.js
- tests/acceptance/order-search-list-test.js
- tests/acceptance/order-state-awaiting-dispatch-test.js
- tests/acceptance/order-state-cancelled-test.js
- tests/acceptance/order-state-close-test.js
- tests/acceptance/order-state-dispatching-test.js
- tests/acceptance/order-state-processing-test.js
https://jira.crossroads.org.hk/browse/GCW-3158
SInce Order is shallow loaded so `Requests` are not loaded in orders `search` page . In this PR we are making request to fetch `gc Requests` on entering order details page.
> GCW-3158-The list of requests on an order incorrectly shows '0' requests until the page is reloaded

- bower.json
- ember-cli-build.js
https://jira.crossroads.org.hk/browse/GCW-3172
The cloudinary dependency had a file which was copied from a blueimp repo, except it was incomplete. We now pull that repo and fetch the file straight from there.
> GCW-3172 Fix jquery upload error

- app/styles/templates/components/_popup_overlay.scss
Disable pointer events on closed overlays. Some edge cases allowed a hidden input field to be focused
> GCW-3190 Fix lost input focus

- app/templates/items/detail/tabs/storage_content.hbs
https://jira.crossroads.org.hk/browse/GCW-3187
BUG: StorageTypeName was not setting which leads to only search "Package" and ignoring `Box`  during assigning Items for Box/Pallet.
> GCW-3187- Cannot search for boxes when adding to a pallet

- app/components/mentionable-message-textbox.js
- app/controllers/orders/conversation.js
- app/templates/orders/_message_template.hbs
https://jira.crossroads.org.hk/browse/GCW-3167
Fixes a minor UI Bug for "the bottom scrollbar arrow and the last user is cut off and can't be seen"
> Minor UI Fix for Names getting sliced

- app/controllers/application.js
- app/controllers/items/index.js
- app/controllers/orders/index.js
- app/services/session.js
- tests/controller/items/index-test.js
- tests/controller/order-index-test.js
https://jira.crossroads.org.hk/browse/GCW-3198
On logout cache was not getting cleared. So, on going to orders or Items index  search page. It tried to show cached key data but data was not available in store because of logout.
This PR clears up cache on logout.
> GCW-3198- Orders don't automatically load when logging in a second time

- app/adapters/gc_organisation.js
- app/controllers/organisations/orders.js
- app/locales/en/translations.js
- app/locales/zh-tw/translations.js
- app/models/gc_organisation.js
- app/routes/organisations/orders.js
- app/services/organisation-service.js
- app/styles/templates/organisations/_search_organisations.scss
- app/templates/organisations/_organisation_tabs.hbs
- app/templates/organisations/orders.hbs
- tests/unit/model/gc_organisation-test.js
https://jira.crossroads.org.hk/browse/GCW-3182
Till now `orders` count for organisation was calculated according to `orders` already loaded in ember-data for any particular organisation.
There was wrong `Orders Count` on:
-  Searched organisation results.
-  On selecting organisation, the count on the `Orders` tab.
This PR fixes:
-  `orders` count dependency on ember-data is removed and fetching `ordersCount` as part of `organisation` model data.
-   Separate  endpoint  endpoint for fetching organisation orders with pagination.
-   CSS fixes for `orders` list.
> GCW-3182-Issues with the Charity/Orders page.

- app/models/packages_location.js
https://jira.crossroads.org.hk/browse/GCW-3218
Currently when an item is moved to a box the default quantity to move is 0, after this change, it will default to the full available quantity of the item.
> GCW-3218 set default-quantity as available while moving item to box

- app/controllers/my_notifications.js
- app/services/messages.js
https://jira.crossroads.org.hk/browse/GCW-3170
Fix Issue: when a comment is read from a different platform or a different browser tab, the unread alerts record doesn't update until the page is reloaded.
> GCW-3170 handle unread-count on notifications screen

- app/styles/templates/_appointments.scss
- app/templates/settings/appointments/_preset_quotas_tab.hbs
- app/templates/settings/appointments/_special_day_quotas_tab.hbs
https://jira.crossroads.org.hk/browse/GCW-2956
In small screens the 'Manage Appointment Quotas' page, it's difficult to select the 3 vertical dots icon, the + and - buttons, and the x button fix .
> GCW-2956-Fix for breaking of icons in small screens for appointment quotas page

- app/controllers/appointments.js
https://jira.crossroads.org.hk/browse/GCW-2957
On the 'Manage Appointment Quotas' page, after selecting a 3 vertical dots icon on a day and opening the dropdown box, if a user goes to the 'Special Dates' tab and returns to the 'Default Quotas' tab, the dropdown box will still be open fix
> GCW-2957-Added fix for dropbox in management quota

- app/models/item.js
- app/services/subscription.js
https://jira.crossroads.org.hk/browse/GCW-3296
This bug was introduced recently, when the subscription code received a "delete" action it would call the `destroyRecord` method. Essentially, tried to delete a record which was already deleted, which caused the bug.
This restores the code as it was.
Stock live updates
> :bug: GCW-3269 live updates don't re-trigger a destroy action

- .circleci/config.yml
Modify the Scandit licensing logic to have one key per environment per platform
> CI: Scandit keys per environment

- app/controllers/orders/detail.js
- app/templates/orders/contact_summary.hbs
Based on comments from Tim on https://jira.crossroads.org.hk/browse/GCW-3275
- Added verification step
- Do not show organisations_user status row for shipments
> GCW-3275 Verify org_user status during finish_processing step

- app/mixins/messages_base.js
https://jira.crossroads.org.hk/browse/GCW-3339
BUG:  While on the 'User' or 'Staff' tab of an order, selecting the 'Send' button while the text field is empty causes the 'The backend responded with an error' pop-up message to appear.
> GCW-3339-Error pops up when a empty message is send fix

- app/controllers/orders/client_summary.js
- app/services/order-service.js
Using `destroyRecord` obfuscates the underlying error message. I simply replaced it with an ajax call
> Fix: Catch error properly when deleting a beneficiary

- app/components/numeric-inline-input.js
https://jira.crossroads.org.hk/browse/GCW-3360
`willDestroyElement` added to destroy component on page change.
> GCW-3360- Using browser/device 'back' button breaks with inline edits

- app/constants/states.js
- app/controllers/order/search_users.js
- app/services/organisations-user-service.js
https://jira.crossroads.org.hk/browse/GCW-3377
Removes the charity user role check on user search, and search user based on `organisations_users` status attribute
> GCW-3377 Remove charity user check from user search

- app/models/item.js
- app/templates/items/detail.hbs
https://jira.crossroads.org.hk/browse/GCW-3293
This PR removes `print_label` button hiding condition.
> GCW-3293-Missing package print label when package undispatched

- .circleci/config.yml
- Rakefile
- fastlane/Fastfile
https://jira.crossroads.org.hk/browse/GCW-3304
FEATURE: Deprecates use of `APP_VERSION` environment variable in the app builds. Delegates to `package.json` instead.
NOTE: Previously, bumping the app version required updating `package.json` and updating `APP_VERSION` in CircleCI. This was was unnecessary duplication and made the builds less automated. After this PR is merged, version will be set entirely from code in the projects `package.json` file and we can delete `APP_VERSION` from CircleCI
- iOS App Store app version
- Google Play app version
> GCW-3304 Depreciate usage of APP_VERSION env variable

- app/controllers/order/search_users.js
- app/templates/order/search_users.hbs
https://jira.crossroads.org.hk/browse/GCW-3292
Adds `organisation_id` in the response so as to update the organisation as well for the order on change of user in contact_summary page
> GCW-3292 Adds organisation_id in the request body

- app/components/goodcity/offers-search-overlay.js
https://jira.crossroads.org.hk/browse/GCW-3179?focusedCommentId=41040&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-41040
BUG: sorting was done on reviewed_at instead of recieved_at
> GCW-3179- QA fix for sorting offers in items page in stock app

- app/components/goodcity/code-search-overlay.js
- app/mixins/async.js
- app/routes/stocktakes/detail.js
- app/routes/stocktakes/index.js
- app/services/package-type-service.js
The package-type preloading was recently removed, which caused parts of the app to break.
I made a cached preload method that can be called anywhere, and added it to the stocktake page.
cc - @bharat619 could you check this : )
> FIX: Introduce codes preloading for stocktake page

- app/styles/app.scss
- app/templates/order/appointment_details.hbs
- app/templates/order/client_information.hbs
- app/templates/order/confirm_booking.hbs
- package.json
- yarn.lock
> Remove dependency of ember-scroll-to-bottom which is deprecated and it causes build failure

- app/routes/orders/detail.js
https://jira.crossroads.org.hk/browse/GCW-3558
This PR fixes issue of not loading `orderTransport` of orders if coming from dashboard. The dashboard does shallow loading which does not load associations. In the Order details page `loadIfAbsent` does not fetch a record if it is already present. So, I have added `findRecord` (without `reload: true`)  instead of `loadIfAbsent` in the logistic Tab to fix this problem.
> GCW-3558- Logistics tab is empty when first viewed

- app/routes/items/detail.js
https://jira.crossroads.org.hk/browse/GCW-3424
Fix below issue
The pop-ups from the 'Process', 'Recycle', 'Trash', 'Gain (increase)', and 'Loss (decrease)' options don't show when selecting the browser's/Pixel's Back button, but selecting the browser's Forward button/reselecting the item causes the pop-up to show again.
> GCW-3424 - Fix pop up issue for the 'Process', 'Recycle', 'Trash', 'Gain (increase)', and 'Loss (decrease)'

- app/controllers/stocktakes/detail.js
- app/templates/stocktakes/detail.hbs
The "stopScanning" method was being called right after an item was added, which prevented the scanner from scanning multiple items
> FIX: re-enable scan multiple on stocktakes

- app/components/camera-detect.js
https://github.com/crossroads/stock.goodcity/issues/1082
This PR changes image type to `jpeg` from `png` for the image taken from `camera-dect` component for mobile web browsers.
Please review this PR and let me know if anything else is required.
> Issue-1082
